---
title: "10_bankbybank_FE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(estimatr)
library(lfe)
library(texreg)

# This file just runs the bank-by-bank regressions with fixed effects, in 
# addition to a bunch of robustness checks. Note that this is not relevant
# for Gov 50 -- this just uses the same data, which is why it's in the same
# repo.

```

```{r}

# Inputting individual bank regressions by adding in dummies for different
# banks and bank types.

most_recent <- readRDS('most_recent_zip_1117.rds') %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(cu = 0) %>%
  mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu)) %>%
  mutate(business_roundtable = ifelse(lender %in%
                                        c("bank of america, national association",
                                          "citibank, n.a.",
                                          "keybank national association",
                                          "jpmorgan chase bank, national association",
                                          "wells fargo bank, national association"),
                                      1, 0)) %>%
  mutate(baml = ifelse(lender == "bank of america, national association",
                       1, 0)) %>%
  mutate(jpm = ifelse(lender == "jpmorgan chase bank, national association",
                       1, 0)) %>%
  mutate(citi = ifelse(lender == "citibank, n.a.",
                       1, 0)) %>%
  mutate(wells = ifelse(lender == "wells fargo bank, national association",
                       1, 0))
  
most_recent_county <-
  readRDS('most_recent_county_1115.rds') %>%
  mutate(baml = ifelse(lender == "bank of america, national association",
                       1, 0)) %>%
  mutate(jpm = ifelse(lender == "jpmorgan chase bank, national association",
                       1, 0)) %>%
  mutate(citi = ifelse(lender == "citibank, n.a.",
                       1, 0)) %>%
  mutate(wells = ifelse(lender == "wells fargo bank, national association",
                       1, 0)) %>%
    mutate(cu = 0) %>%
    mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1,
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1,
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1,
                              cu)) %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(cu = 0) %>%
  mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu)) %>%
  mutate(business_roundtable = ifelse(lender %in%
                                        c("bank of america, national association",
                                          "citibank, n.a.",
                                          "keybank national association",
                                          "jpmorgan chase bank, national association",
                                          "wells fargo bank, national association"),
                                      1, 0)) %>%
  mutate(baml = ifelse(lender == "bank of america, national association",
                                      1, 0))

# This is for one of the robustness checks where I replace
# ZIP-level estimated data with county estimated data.

most_recent_both <- readRDS('most_recent_zip_withcounties_1118.rds') %>%
    mutate(baml = ifelse(lender == "bank of america, national association",
                       1, 0)) %>%
  mutate(jpm = ifelse(lender == "jpmorgan chase bank, national association",
                       1, 0)) %>%
  mutate(citi = ifelse(lender == "citibank, n.a.",
                       1, 0)) %>%
  mutate(wells = ifelse(lender == "wells fargo bank, national association",
                       1, 0)) %>%
  mutate(fips = as.factor(fips),
         zip = as.factor(zip)) %>%
    mutate(cu = 0) %>%
    mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1,
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1,
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1,
                              cu)) %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(business_roundtable = ifelse(lender %in%
                                        c("bank of america, national association",
                                          "citibank, n.a.",
                                          "keybank national association",
                                          "jpmorgan chase bank, national association",
                                          "wells fargo bank, national association"),
                                      1, 0))
```

```{r}

# This series of regressions excludes all the interaction terms except between
# bank and race. There are later, unused regressions that also put in
# extra interaction terms.

baml_reg_only <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       baml + I(baml * minority_percent)|fips|0|zip, 
    data = most_recent)

jpm_reg_only <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent)|fips|0|zip, 
    data = most_recent)

citi_reg_only <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       citi + I(citi * minority_percent)|fips|0|zip, 
    data = most_recent)

wells_reg_only <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       wells + I(wells * minority_percent)|fips|0|zip, 
    data = most_recent)

cu_reg_only <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       cu + I(cu * minority_percent)|fips|0|zip, 
    data = most_recent)

national_reg_only <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + I(national * minority_percent)|fips|0|zip, 
    data = most_recent)
```


```{r}

# These regressions end up being unused because of the high correlation 
# between the interaction terms.

baml_reg <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       baml + I(baml * minority_percent) + 
       I(baml * median_family_income) +
       I(baml * unemployment_rate)|fips|0|zip + fips, 
    data = most_recent)

```

```{r}
jpm_reg <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent) + 
       I(jpm * median_family_income) +
       I(jpm * unemployment_rate)|fips|0|zip + fips, 
    data = most_recent)
```


```{r}
citi_reg <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       citi + I(citi * minority_percent) + 
       I(citi * median_family_income) +
       I(citi * unemployment_rate)|fips|0|zip + fips, 
    data = most_recent)
```


```{r}
wells_reg <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       wells + I(wells * minority_percent) + 
       I(wells * median_family_income) +
       I(wells * unemployment_rate)|fips|0|zip + fips, 
    data = most_recent)
```


```{r}
cu_reg <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       cu + I(cu * minority_percent) + 
       I(cu * median_family_income) +
       I(cu * unemployment_rate)|fips|0|zip + fips, 
    data = most_recent)
```


```{r}
national_reg <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + I(national * minority_percent) + 
       I(national * median_family_income) +
       I(national * unemployment_rate)|fips|0|zip + fips, 
    data = most_recent)
```

```{r}

roundtable_reg1_fix <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + cu + business_roundtable +
      I(business_roundtable * minority_percent)|fips|0|zip, 
    data = most_recent)


roundtable_reg2 <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + cu + business_roundtable +
    I(national * minority_percent) + 
    I(business_roundtable * minority_percent)|fips|0|zip + fips, 
    data = most_recent)
```


```{r}
# Redoing county level with felm just to make sure everything's correct

county_roundtable1 <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
      national +
      cu +
       business_roundtable+ I(business_roundtable* minority_percent)|0|0|fips,
    data = most_recent_county)

county_roundtable2 <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
      national +
      I(national * minority_percent) +
      cu +
       business_roundtable+ I(business_roundtable * minority_percent)|0|0|fips,
    data = most_recent_county)
```


```{r}
# banks county

baml_county <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       baml + I(baml * minority_percent)|0|0|fips,
    data = most_recent_county)

citi_county <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       citi + I(citi * minority_percent)|0|0|fips,
    data = most_recent_county)

jpm_county <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent)|0|0|fips,
    data = most_recent_county)

wells_county <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       wells + I(wells * minority_percent)|0|0|fips,
    data = most_recent_county)
```

```{r}
national_county <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + I(national * minority_percent)|0|0|fips,
    data = most_recent_county)

cu_county <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       cu + I(cu * minority_percent)|0|0|fips,
    data = most_recent_county)
```

```{r}

# Robustness check w/ zip and county

# baml_reg_check <- felm(
#     business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent +
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     county_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     county_unemployment_rate_apr + 
#     county_unemployment_rate + 
#     mean_start_cases +
#     mean_start_deaths + 
#     mean_end_cases +
#     mean_end_deaths + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     baml + I(baml * minority_percent) + 
#        I(baml * median_family_income) +
#        I(baml * unemployment_rate)|0|0|zip + fips,
#   data = most_recent_both)
```

```{r}
baml_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + baml + I(baml*minority_percent)|fips|0|zip, 
    data = most_recent)

citi_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
     cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement +
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr +
    non_essential_closure_current + 
       citi + I(citi * minority_percent)|0|0|zip + fips, 
    data = most_recent_both)

# jpm_reg_check <- felm(
#     business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent +
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     county_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     county_unemployment_rate_apr + 
#     county_unemployment_rate + 
#     mean_start_cases +
#     mean_start_deaths + 
#     mean_end_cases +
#     mean_end_deaths + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     citi + I(citi * minority_percent) + 
#        I(citi * median_family_income) +
#        I(citi * unemployment_rate)|0|0|zip + fips,
#   data = most_recent_both)
```

```{r}
jpm_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
     cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement +
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr +
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent)|0|0|zip + fips, 
    data = most_recent_both)

# citi_reg_check <- felm(
#     business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent +
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     county_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     county_unemployment_rate_apr + 
#     county_unemployment_rate + 
#     mean_start_cases +
#     mean_start_deaths + 
#     mean_end_cases +
#     mean_end_deaths + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     jpm + I(jpm * minority_percent) + 
#        I(jpm * median_family_income) +
#        I(jpm * unemployment_rate)|0|0|zip + fips,
#   data = most_recent_both)
```


```{r}
wells_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
     cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement +
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr +
    non_essential_closure_current + 
       citi + I(citi * minority_percent)|0|0|zip + fips, 
    data = most_recent_both)

# wells_reg_check <- felm(
#     business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent +
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     county_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     county_unemployment_rate_apr + 
#     county_unemployment_rate + 
#     mean_start_cases +
#     mean_start_deaths + 
#     mean_end_cases +
#     mean_end_deaths + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     wells + I(wells * minority_percent) + 
#        I(wells * median_family_income) +
#        I(wells * unemployment_rate)|0|0|zip + fips,
#   data = most_recent_both)
```


```{r}
national_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
     cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement +
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr +
    non_essential_closure_current + 
       wells + I(wells * minority_percent)|0|0|zip + fips, 
    data = most_recent_both)

# cu_reg_check <- felm(
#     business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent +
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     county_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     county_unemployment_rate_apr + 
#     county_unemployment_rate + 
#     mean_start_cases +
#     mean_start_deaths + 
#     mean_end_cases +
#     mean_end_deaths + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     national + I(national * minority_percent) + 
#        I(national * median_family_income) +
#        I(national * unemployment_rate)|0|0|zip + fips,
#   data = most_recent_both)
```


```{r}
cu_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
     cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement +
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr +
    non_essential_closure_current + 
       cu + I(cu * minority_percent)|0|0|zip + fips, 
    data = most_recent_both)

# national_reg_check <- felm(
#     business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent +
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     county_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     county_unemployment_rate_apr + 
#     county_unemployment_rate + 
#     mean_start_cases +
#     mean_start_deaths + 
#     mean_end_cases +
#     mean_end_deaths + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     cu + I(cu * minority_percent) + 
#        I(cu * median_family_income) +
#        I(cu * unemployment_rate)|0|0|zip + fips,
#   data = most_recent_both)
```


```{r}
business_roundtable_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
 cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement +
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr +
    non_essential_closure_current + 
       national + I(national * minority_percent)|0|0|zip + fips, 
    data = most_recent_both)

```

```{r}

# roundtable check

# roundtable1_check <- felm(    business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent +
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     county_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     county_unemployment_rate_apr + 
#     county_unemployment_rate + 
#     mean_start_cases +
#     mean_start_deaths + 
#     mean_end_cases +
#     mean_end_deaths + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     national + 
#     cu +
#     business_roundtable + I(business_roundtable * minority_percent) + 
#        I(business_roundtable * median_family_income) +
#        I(business_roundtable * unemployment_rate)|0|0|zip + fips,
#   data = most_recent_both)
```


```{r}
business_roundtable_check2 <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
     cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement +
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr +
    non_essential_closure_current + 
      cu + national +
       business_roundtable + 
      I(business_roundtable * minority_percent)|0|0|zip + fips, 
    data = most_recent_both)

# roundtable2_check <- felm(    business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent +
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     county_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     county_unemployment_rate_apr + 
#     county_unemployment_rate + 
#     mean_start_cases +
#     mean_start_deaths + 
#     mean_end_cases +
#     mean_end_deaths + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     national + 
#     I(national * minority_percent) + 
#     cu +
#     business_roundtable + I(business_roundtable * minority_percent)|0|0|zip + fips,
#   data = most_recent_both)

```

```{r}

# Trying bank-specific w/ deposits -- this isn't in the initial setup
# part because I thought to do this a little bit later than the others.

# Read the file in if you have to

most_recent_deposits <- readRDS('most_recent_zip_banksmatched_1128.rds') %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(business_roundtable = ifelse(lender %in%
                                        c("bank of america, national association",
                                          "citibank, national association.",
                                          "keybank national association",
                                          "jpmorgan chase bank, national association",
                                          "wells fargo bank, national association"),
                                      1, 0)) %>%
  mutate(fips = as.factor(fips)) %>%
  mutate(dep = dep / 100000) %>%
  mutate(baml = ifelse(lender == "bank of america, national association",
                       1, 0)) %>%
  mutate(jpm = ifelse(lender == "jpmorgan chase bank, national association",
                       1, 0)) %>%
  mutate(citi = ifelse(lender == "citibank, national association",
                       1, 0)) %>%
  mutate(wells = ifelse(lender == "wells fargo bank, national association",
                       1, 0))
  
  
  


```

```{r}

# Bank-specific, including deposits

baml_dep <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       baml + I(baml * minority_percent) +
      national + I(national * minority_percent) + 
      dep + I(dep * minority_percent)|fips|0|zip, 
    data = most_recent_deposits)

citi_dep <- felm(
    business_days ~ 1 +
    median_family_income +
    minority_percent +
    high_school_pct +
    married_percent + male_percent +
    cook_pvi +
    rural +
    estimate_gini_index +
    violent_crime_rate +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil +
    loan_5mil_10mil +
    bank_ppp_issued +
    jobs_reported +
    banks_per_pop +
    businesses_per_pop +
    payroll +
    unemployment_rate_apr +
    unemployment_rate +
    mean_start_cases_weighted +
    mean_start_deaths_weighted +
    mean_end_cases_weighted +
    mean_end_deaths_weighted +
    stay_at_home_apr +
    stay_at_home_current +
    non_essential_closure_apr +
    non_essential_closure_current +
       citi + I(citi * minority_percent) +
      national + I(national * minority_percent) +
      dep + I(dep * minority_percent)|fips|0|zip,
    data = most_recent_deposits)
```

```{r}
jpm_dep <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent) +
      national + I(national * minority_percent) + 
      dep + I(dep * minority_percent)|fips|0|zip, 
    data = most_recent_deposits)

wells_dep <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       wells + I(wells * minority_percent) +
      national + I(national * minority_percent) + 
      dep + I(dep * minority_percent)|fips|0|zip, 
    data = most_recent_deposits)
```

```{r}
national_dep <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + I(national * minority_percent) +
      dep + I(dep * minority_percent)|fips|0|zip, 
    data = most_recent_deposits)
```



```{r}

roundtable_deposits <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued +
    dep + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + business_roundtable +
      I(business_roundtable * minority_percent) +
      I(national * minority_percent) + 
      I(dep * minority_percent)|fips|0|zip, 
    data = most_recent_deposits)

roundtable_deposits_2 <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued +
    dep + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + business_roundtable +
      I(business_roundtable * minority_percent) + 
      I(dep * minority_percent)|fips|0|zip, 
    data = most_recent_deposits)

```

```{r}

# Trying without preference and requirement variables -- i.e., using the 
# original 3.7 million loan dataset

most_recent <- readRDS('most_recent_zip_nobanks_1126.rds') %>%
  mutate(lender = tolower(lender)) %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(cu = 0) %>%
  mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu)) %>%
  mutate(business_roundtable = ifelse(lender %in%
                                        c("bank of america, national association",
                                          "citibank, n.a.",
                                          "keybank national association",
                                          "jpmorgan chase bank, national association",
                                          "wells fargo bank, national association"),
                                      1, 0)) %>%
  mutate(baml = ifelse(lender == "bank of america, national association",
                       1, 0)) %>%
  mutate(jpm = ifelse(lender == "jpmorgan chase bank, national association",
                       1, 0)) %>%
  mutate(citi = ifelse(lender == "citibank, n.a.",
                       1, 0)) %>%
  mutate(wells = ifelse(lender == "wells fargo bank, national association",
                       1, 0))
  
```

```{r}
roundtable_orig1 <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + cu + business_roundtable +
      I(business_roundtable * minority_percent)|fips|0|zip, 
    data = most_recent)

roundtable_orig2 <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + cu + business_roundtable +
      I(business_roundtable * minority_percent) +
      I(national * minority_percent)|fips|0|zip, 
    data = most_recent)

```

```{r}

# Doing the bank checks here, too

baml_orig <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       baml + I(baml * minority_percent)|fips|0|zip, 
    data = most_recent)

citi_orig <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       citi + I(citi * minority_percent)|fips|0|zip, 
    data = most_recent)

jpm_orig <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent)|fips|0|zip, 
    data = most_recent)
```

```{r}
wells_orig <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       wells + I(wells * minority_percent)|fips|0|zip, 
    data = most_recent)

national_orig <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + I(national * minority_percent)|fips|0|zip, 
    data = most_recent)

cu_orig <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       cu + I(cu * minority_percent)|fips|0|zip, 
    data = most_recent)
```

```{r}

# Trying yet another robustness check -- simply just running the bank
# regressions with the national and cu stuff built in

baml_robust <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       baml + I(baml * minority_percent) +
      national + cu + I(national * minority_percent)|fips|0|zip, 
    data = most_recent)

citi_robust <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       citi + I(citi * minority_percent) +
      national + cu + I(national * minority_percent)|fips|0|zip, 
    data = most_recent)
```

```{r}
jpm_robust <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent) +
      national + cu + I(national * minority_percent)|fips|0|zip, 
    data = most_recent)

wells_robust <- felm(
    business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       wells + I(wells * minority_percent) +
      national + cu + I(national * minority_percent)|fips|0|zip, 
    data = most_recent)
```

