---
title: "10_bankbybank"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(broom)
library(estimatr)
library(texreg)
library(ggeffects)
#library(readxl)
```

```{r}
# Load up the data for most recent stuff, as usual

most_recent <- readRDS('most_recent_zip_1115.rds') %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
   mutate(cu = 0) %>%
  mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu)) %>%
  mutate(business_roundtable = ifelse(lender %in%
                                        c("bank of america, national association",
                                          "citibank, n.a.",
                                          "keybank national association",
                                          "jpmorgan chase bank, national association",
                                          "wells fargo bank, national association"),
                                      1, 0)) %>%
  mutate(baml = ifelse(lender == "bank of america, national association",
                       1, 0)) %>%
  mutate(jpm = ifelse(lender == "jpmorgan chase bank, national association",
                       1, 0)) %>%
  mutate(citi = ifelse(lender == "citibank, n.a.",
                       1, 0)) %>%
  mutate(wells = ifelse(lender == "wells fargo bank, national association",
                       1, 0))
  

most_recent_county <- readRDS('most_recent_county_1115.rds')
```

```{r}
baml_reg <- lm_robust(
       business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       baml + I(baml * minority_percent) + 
       I(baml * median_family_income) +
       I(baml * unemployment_rate), most_recent, clusters = zip, se_type = "CR0")

```

```{r}
jpm_reg <- lm_robust(
       business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent) + 
       I(jpm * median_family_income) +
       I(jpm * unemployment_rate), most_recent, clusters = zip, se_type = "CR0")

```


```{r}
# citi <- most_recent %>%
#   mutate(citi = ifelse(lender == "citibank, n.a.",
#                        1, 0))

citi_reg <- lm_robust(
       business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       citi + I(citi * minority_percent) + 
       I(citi * median_family_income) +
       I(citi * unemployment_rate), most_recent, clusters = zip, se_type = "CR0")
```


```{r}
# wells <- most_recent %>%
#   mutate(wells = ifelse(lender == "wells fargo bank, national association",
#                        1, 0))

wells_reg <- lm_robust(
       business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       wells + I(wells * minority_percent) + 
       I(wells * median_family_income) +
       I(wells * unemployment_rate), most_recent, clusters = zip, se_type = "CR0")
```


```{r}
# Dummy coding for credit union
# credit_union <- most_recent %>%
#     mutate(cu = 0) %>%
#     mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
#                               cu),
#          cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
#                               cu),
#          cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
#                               cu))

credit_union_reg <- lm_robust(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       cu + I(cu * minority_percent) + 
       I(cu * median_family_income) +
       I(cu * unemployment_rate), most_recent, clusters = zip, se_type = "CR0")

```
```{r}
# Doing national banks reg

national_reg <- lm_robust(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national+ I(national* minority_percent) + 
       I(national* median_family_income) +
       I(national* unemployment_rate), 
    most_recent, clusters = zip, se_type = "CR0")
```


```{r}
national_bank_graph <- ggeffect(national_reg, terms = c("national", "minority_percent"))
```

```{r}
# Business roundtable effect

roundtable_reg <- lm_robust(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national +
      cu +
      business_roundtable +
      I(business_roundtable * minority_percent) +
      I(business_roundtable * median_family_income) +
      I(business_roundtable * unemployment_rate),
    most_recent, clusters = zip, se_type = "CR0")
```


```{r}

# including both interaction terms

roundtable_reg_2 <- lm_robust(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national +
      cu +
      business_roundtable +
      I(national * minority_percent) + 
      I(business_roundtable * minority_percent),
    most_recent, clusters = zip, se_type = "CR0")
```


```{r}
# COUNTIES indicator variables

banks_county <- most_recent_county %>%
  mutate(baml = ifelse(lender == "bank of america, national association",
                       1, 0)) %>%
  mutate(jpm = ifelse(lender == "jpmorgan chase bank, national association",
                       1, 0)) %>%
  mutate(citi = ifelse(lender == "citibank, n.a.",
                       1, 0)) %>%
  mutate(wells = ifelse(lender == "wells fargo bank, national association",
                       1, 0)) %>%
    mutate(cu = 0) %>%
    mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu)) %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(business_roundtable = ifelse(lender %in%
                                        c("bank of america, national association",
                                          "citibank, n.a.",
                                          "keybank national association",
                                          "jpmorgan chase bank, national association",
                                          "wells fargo bank, national association"),
                                      1, 0))
```


```{r}
baml_reg_county <- lm_robust(
       business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       baml + I(baml * minority_percent) + 
       I(baml * median_income) +
       I(baml * unemployment_rate_percent), banks_county, 
    clusters = fips, se_type = "CR0")


citi_reg_county <- lm_robust(
       business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       citi + I(citi * minority_percent) + 
       I(citi * median_income) +
       I(citi * unemployment_rate_percent), banks_county, 
    clusters = fips, se_type = "CR0")

jpm_reg_county <- lm_robust(
       business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       jpm + I(jpm * minority_percent) + 
       I(jpm * median_income) +
       I(jpm * unemployment_rate_percent), 
    banks_county, clusters = fips, se_type = "CR0")

wells_reg_county <- lm_robust(
       business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       wells + I(wells * minority_percent) + 
       I(wells * median_income) +
       I(wells * unemployment_rate_percent), banks_county, 
    clusters = fips, se_type = "CR0")

credit_union_reg <- lm_robust(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       cu + I(cu * minority_percent) + 
       I(cu * median_income) +
       I(cu * unemployment_rate_percent), 
    banks_county, clusters = fips, se_type = "CR0")

national_reg <- lm_robust(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national+ I(national* minority_percent) + 
       I(national* median_income) +
       I(national* unemployment_rate_percent), 
    banks_county, clusters = fips, se_type = "CR0")
```

```{r}
# Business roundtable reg

county_roundtable_reg <- lm_robust(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
      national +
      cu +
       business_roundtable+ I(business_roundtable* minority_percent) + 
       I(business_roundtable* median_income) +
       I(business_roundtable* unemployment_rate_percent), 
    banks_county, clusters = fips, se_type = "CR0")
```


```{r}

# Adding in both interaction terms at once

county_roundtable_reg_2 <- lm_robust(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
      national +
      cu +
       business_roundtable + 
      I(business_roundtable * minority_percent) + 
      I(national * minority_percent), 
    banks_county, clusters = fips, se_type = "CR0")
```


```{r}
national_bank_graph_county <- ggeffect(national_reg, 
                                       terms = c("national", "minority_percent"))

```

