---
title: "shiny"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggeffects)
library(janitor)
library(lubridate)
library(bizdays)
library(openintro)
library(fixest)
library(estimatr)


# cal <- create.calendar(name = "mycal", weekdays=c("saturday", "sunday"))

# This file is purely experimental -- me pulling out chunks of a shiny app
# run in an rmd or prepping files for the shiny app
```


```{r}
# Reading in the data. I"m just doing this so I can use ggeffect later

most_recent <- readRDS('most_recent_zip_nobanks_1130.rds') %>%
  mutate(state = as.factor(state),
         fips = as.factor(fips),
         lender = as.factor(lender)) %>%
   mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(cu = 0) %>%
  mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu))

most_recent <- readRDS('most_recent_zip_1130.rds') %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(cu = 0) %>%
  mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu))

most_recent_county <- readRDS('most_recent_county_nobanks_1130.rds') %>%
    mutate(state = as.factor(state),
         fips = as.factor(fips),
         lender = as.factor(lender))

most_recent_county <- readRDS('most_recent_county_1130.rds') %>%
    mutate(state = as.factor(state),
         fips = as.factor(fips),
         lender = as.factor(lender)) %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(cu = 0) %>%
  mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu))
```

```{r}
# Adding in the race days stuff

race <- read_csv("raw_data/acs_race/ACSDP5Y2018.DP05_data_with_overlays_2020-10-12T162449.csv",
                skip = 1) %>%
  clean_names() %>%
  dplyr::select(geographic_area_name, 
                    percent_estimate_race_total_population_one_race_white) %>%
  mutate(geographic_area_name = map_chr(geographic_area_name, ~ substring(., 6)),
         percent_estimate_race_total_population_one_race_white = 
           as.double(percent_estimate_race_total_population_one_race_white)) %>%
  mutate(geographic_area_name = 
           str_trim(geographic_area_name, side = "both")) %>%
  mutate(minority_percent = 
           100 - percent_estimate_race_total_population_one_race_white) %>%
  dplyr::select(-percent_estimate_race_total_population_one_race_white)
```

```{r}
ppp_150 <- read_csv("raw_data/sba/PPP_SBA_150.csv") %>%
  clean_names() %>%
  select(loan_range, zip, date_approved, lender, address, city, state,
         jobs_reported) %>%
  drop_na(zip, jobs_reported) %>%
  
  # This calculates the date on which loans were approved vs. when apps opened.
  mutate(date_approved = mdy(date_approved), 
         days_to_approval = date_approved - mdy("04/03/2020"),
         zip = as.character(zip))

ppp_150_newcol <- ppp_150 %>%
  mutate(loan_amount = NA) %>%
  mutate(loan_amount = as.character(loan_amount))

sba_cleaning <- function(file) {
  x <- read_csv(file, col_types = cols()) %>%
    clean_names() %>%
    select(loan_amount, zip, date_approved, lender, city, state,
           jobs_reported) %>%
    drop_na(zip, jobs_reported) %>%
    mutate(date_approved = mdy(date_approved), 
         days_to_approval = date_approved - mdy("04/03/2020"),
         zip = as.character(zip))
}

# run for Mac

file.names1 <- dir(path = "/Users/Regular/Desktop/GOV50/pppdata/raw_data/sba/states/", pattern = ".csv")

# run for Windows

file.names2 <- dir(path = "C:/Justin/Gov50/pppdata/raw_data/sba/states/", pattern = ".csv")

all_states<- tibble()

for(i in 1:length(file.names2)) {
  file <- sba_cleaning(paste("raw_data/sba/states/",file.names2[i], sep = ""))
  all_states <- rbind(all_states, file)
}

all_states2 <- all_states %>%
  mutate(loan_range = "less than 150k", address = NA)

ppp_total <- rbind(ppp_150_newcol, all_states2)
```


```{r}
loan_race <- left_join(ppp_total, race, 
                       by = c("zip" = "geographic_area_name")) %>%
  drop_na(minority_percent) %>%
  drop_na(state) %>%
  select(state, date_approved, minority_percent) %>%
  mutate(business_days = bizdays(as.Date("2020-04-03"), date_approved, 
                                 'mycal')) %>%
  mutate(cuts = cut(minority_percent,
                    seq(0, 100, by = 10))) %>%
  select(- minority_percent)

national <- loan_race %>%
  group_by(cuts) %>%
  summarize(mean_days = mean(business_days), .groups = "drop") %>%
  mutate(state = "National")

states <- loan_race %>%
  group_by(state, cuts) %>%
  summarize(mean_days = mean(business_days), .groups = "drop")

race_days3 <- rbind(national, states)
```

```{r}

# Don't run the lm-robust -- seems like there are documented issues here.

set.seed(9)
sample <- sample_n(most_recent, size = 500000) %>%
  mutate(zip = as.factor(zip),
         lender = as.factor(lender),
         state = as.factor(zip),
         fips = as.factor(fips))

most_recent <- most_recent %>%
  mutate(zip = as.factor(zip),
         lender = as.factor(lender),
         state = as.factor(zip),
         fips = as.factor(fips))

covid_fe <- lm_robust(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + renter_percent + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current, fixed_effects = ~ lender + state,
    clusters = zip, data = sample, se_type = "stata")
```

```{r}
# This should work better given documented issues with lm-robust and ggeffect
# Again, ram problems :()

covid <- lm(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + renter_percent + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + factor(state), 
    data = sample)
```
```{r}

```



```{r}

covid <- feols(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + renter_percent +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current|fips + lender,
  data = most_recent)

# sq <- felm(
#   business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent + 
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     violent_crime_rate + 
#     delay +
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     unemployment_rate_apr + 
#     unemployment_rate + 
#     mean_start_cases_weighted +
#     mean_start_deaths_weighted + 
#     mean_end_cases_weighted +
#     mean_end_deaths_weighted + 
#     stay_at_home_apr + 
#     stay_at_home_current + 
#     non_essential_closure_apr + 
#     non_essential_closure_current +
#     I(minority_percent^2)|fips + lender|0|zip,
#   data = sample)
```

```{r}
# Let's try ggeffects now

covid <- lm_robust(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + renter_percent +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current,
  clusters = zip, data = most_recent)

sq <- lm_robust(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + renter_percent +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + I(minority_percent^2),
  clusters = zip, data = most_recent)
```

```{r}
marg_race_sq <- ggeffect(sq, terms = "minority_percent")
```

```{r}
county_covid <- lm_robust(
  business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current,
  most_recent_county, clusters = fips, se_type = "stata")

county_interactions <- lm_robust(
  business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2),
  most_recent_county, clusters = fips, se_type = "stata")
```


```{r}
marginal_race_county <- ggeffect(county_covid, 
                                    terms = "minority_percent")
```


```{r}

# Now do for banks as well

national_reg <- lm_robust(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + renter_percent + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
    national+ I(national* minority_percent), 
    most_recent, clusters = zip, se_type = "stata")
```

```{r}
national_bank_graph <- ggeffect(national_reg, 
                                terms = c("national", "minority_percent"))

```

```{r}
national_reg <- lm_robust(business_days ~ 1 + 
    median_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + renter_percent + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national+ I(national* minority_percent), 
    most_recent_county, clusters = fips, se_type = "stata")
```

```{r}
national_bank_graph_county <- ggeffect(national_reg, 
                                terms = c("national", "minority_percent"))
```

```{r}

# Also doing ggeffects for the ownership regression, again w/o fixed
# effects :((

# You might need to run this in Server for it to work properly sadly

most_recent_ownership <- 
  readRDS('most_recent_county_nobanks_ownership.rds') %>%
  mutate(fips = as.factor(fips))

biz_reg <- lm_robust(business_days ~ 1 + median_income + 
    percent_minority_biz + 
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + renter_percent +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent +
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current, 
    clusters = fips, data = most_recent_ownership, se_type = "stata")
```

```{r}
marg_race_biz <- ggeffect(biz_reg, terms = "percent_minority_biz")
```

```{r}
biz_reg_sq <- lm_robust(business_days ~ 1 + median_income + 
    percent_minority_biz + 
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + renter_percent +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent +
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
    I(percent_minority_biz^2), 
    clusters = fips, data = most_recent_ownership, se_type = "stata")
```

```{r}
marg_race_biz_sq <- ggeffect(biz_reg_sq, terms = "percent_minority_biz")

```


```{r}
latest_state_cases <- read_csv('COVIDPPP/us-states.csv', col_types = cols()) %>%
  mutate(state_abb = state2abbr(state)) %>%
  select(-fips)

latest_state_cases %>%
  filter(state_abb == "AZ") %>%
  ggplot(aes(x = date, y = cases)) +
    geom_line(color = "dodgerblue") +
    labs(x = "Month", y = "Cases",
         #title =  paste("Daily New COVID-19 Cases,", input$stateInput2),
         caption = "Source: New York Times") + 
    theme(legend.position = "none") + 
    scale_x_date(breaks = c(as.Date("2020/02/01"),
                                  as.Date("2020/03/01"),
                                  as.Date("2020/04/01"),
                                  as.Date("2020/05/01"),
                                  as.Date("2020/06/01"),
                                  as.Date("2020/07/01"),
                                  as.Date("2020/08/01"),
                                  as.Date("2020/09/01"),
                                  as.Date("2020/10/01"),
                                  as.Date("2020/11/01")),
                 labels = c("Feb", "Mar", "Apr",
                            "May", "Jun", "Jul", "Aug",
                            "Sept", "Oct", "Nov")) + 
    scale_y_continuous(breaks = scales::pretty_breaks(n = 10), 
                       label = scales::comma) + 
    theme_classic()
  
```
Writing equation:


$$y_i = \alpha_{locality} + \beta minority + X'_i\gamma + \epsilon_i$$

```{r}
# Trying graphing my marginal race stuff

marg_race <- readRDS('marg_race.rds')

marg_race %>%
  ggplot(aes(x = x, y = predicted)) +
          geom_line(color = "darkblue") +
          geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .2) +
          labs(x = "Minority Proportion of Population (Percent)", 
               y = "Predicted Wait Time (Business Days)",
               title = "Linear Predicted Effect of Racial Minority Presence on Wait Times
               (Grouping by ZIP Codes)") +
          xlim(0, 100) +
          theme_classic()
```


