---
title: "Matching Banks"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(openintro)

# Here, we're adding in deposit values for banks as a robustness check
# for CSR agreement effectiveness. THIS IS NOT PART OF THE GOV 50 shiny app,
# only for other projects for my other classes using the same data.

```

```{r}

# Read in the most recent dataset we have - about 3.7 million loans. We
# replace n.a. to make later matching easier.

most_recent <- readRDS('most_recent_zip_nobanks_1126.rds') %>%
  mutate(lender = tolower(lender), id = seq.int(n())) %>%
  mutate(lender = str_replace(lender, pattern = "n.a.", 
                              replacement = "national association")) %>%
  mutate(lender = str_trim(lender, side = "both"))
  

```

```{r}
# Basic data cleaning to make our matching easier a little bit later.

deposits <- read_csv('raw_data/fdic/All_Reports_20200630_Total_Deposits.csv',
                     col_types = cols()) %>%
  clean_names() %>%
  mutate(name = tolower(name), dep = as.double(dep)) %>%
  mutate(name = str_trim(name, side = "both")) %>%
  select(cert, name, city, stalp, dep)

# This will come in handy a little bit later -- we don't actually use this
# yet until we try to deduplicate duplicated loans.

locations <- read_csv('raw_data/fdic/OFFICES2_PART2.csv',
                      col_types = cols()) %>%
  clean_names() %>%
  select(cert, stname) %>%
  group_by(cert) %>%
  distinct(stname) %>%
  mutate(state = state2abbr(stname)) %>%
  select(-stname) %>%
  summarize(state_list = list(state), .groups = "drop")

bank_deposit_locations <- left_join(deposits, locations, by = "cert") %>%
  filter(state_list != "NULL") %>%
  select(-city, -stalp, -name) %>%
  mutate(cert = as.character(cert))



```

```{r}

# sba_banks <- most_recent %>%
#   select(lender) %>%
#   distinct()
# 
# matched_lenders <- left_join(sba_banks, bank_deposit_locations, 
#                                    by = c("lender" = "name"))
  

```

```{r}

# Let's try a straight join and see what happens first. This matches
# most of the loans we end up using -- most banks are correctly matched.

deposits_joined <- left_join(most_recent, deposits, 
                             by = c("lender" = "name")) %>%
  drop_na(dep) %>%
  group_by(id) %>%
  
  # We filter for duplicates and then split this into two tibbles.
  
  mutate(duplicates = n()) %>%
  ungroup()

deposits_noduplicate <- deposits_joined %>%
  filter(duplicates == 1) %>%
  mutate(cert = as.character(cert))

deposits_duplicate <- deposits_joined %>%
  filter(duplicates > 1) %>%
  mutate(cert = as.character(cert))
```


```{r}

# The noduplicate file is already finalized. Now we're working with the 
# duplicated ones. We match these to the list of bank locations I have
# from the FDIC -- this ends up dropping a bunch since the FDIC I guess
# doesn't track locations for some banks.

states_matching <- left_join(deposits_duplicate, bank_deposit_locations,
                             by = "cert") %>%
  drop_na(dep.y) %>%
  select(-dep.x, -city.y) %>%
  rename("dep" = "dep.y", "city" = "city.x") %>%
  drop_na(state_list, state) %>%
  mutate(state = as.character(state)) %>%
  
  # Then we create a logical for whether the state the loan was acquired in
  # is one of the states where the "matched" bank has an office. We do this
  # to attempt to eliminate cases where identically named banks in 
  # different parts of the country are matched, so we can get rid of 
  # some of the duplicates
  
  mutate(in_state = str_detect(state_list, pattern = state))

# We then count duplicates AGAIN to see if we've gotten some more decisively
# matched loans. This isn't fully accurate, because you might have crossed
# state lines to get a loan, but it's probably mostly there. This only adds on
# about 75k additional loans to our analysis, because it's very limited.

deposits_dedup <- states_matching %>%
  filter(in_state == TRUE) %>%
  select(-in_state) %>%
  group_by(id) %>%
  mutate(duplicates = n()) %>%
  ungroup()

deposits_cleaned <- deposits_dedup %>%
  filter(duplicates == 1) %>%
  select(-state_list)

# deposits_dirty <- deposits_dedup %>%
#   filter(duplicates > 1)

# This preps the noduplicate file for a rowbind by matching up column types
# and names.

deposits_noduplicate <- deposits_noduplicate %>%
  mutate(state = as.character(state)) %>%
  select(-city.y) %>%
  rename("city" = "city.x")

deposits_filtered <- rbind(deposits_noduplicate, deposits_cleaned)

# remaining_banks <- deposits_dirty %>%
#   select(lender, state, state_list, cert) %>%
#   distinct()

```

```{r}
# We also take the opportunity to add in loan numbers, something we exclude
# from the original dataset since we were just using lender fixed effects.

old_data <- readRDS('ppp_loanonly_all_loans.rds')

loan_numbers <- old_data %>%
  select(lender) %>%
  group_by(lender) %>%
  summarize(bank_ppp_issued = n(), .groups = "drop") %>%
  mutate(lender = tolower(lender))

```

```{r}
deposits_loannumbers <- 
  left_join(deposits_filtered, loan_numbers, by = "lender") %>%
  group_by(id) %>%
  mutate(duplicates = n()) %>%
  ungroup() %>%
  filter(duplicates == 1)
```


```{r}

# DOn't need this code -- was just looking at which banks had duplicates.

deposits_joined <- left_join(deposits_filtered, loan_numbers,
                             by = "lender") %>%
  select(-cert, -state_list)

deposits_joined <- distinct(deposits_joined)

deposits_joined %>%
  group_by(id) %>%
  mutate(duplicates = n()) %>%
  ungroup() %>%
  filter(duplicates > 1)
```

