---
title: "Using final data cleaning"
author: "Justin Qi"
date: "10/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)
library(stringr)

#zip_data <- readRDS("zip_ppp_allstates_1018.rds")

# This just ended up being one file by itself because I was originally
# including other things and decided not to. This just creates
# dummies that I actually end up renaming a little bit later anyway.

```


```{r}
# included in latest now -- this is just making dummies based on loan size 
# (I actually rename these later but I've preserved this for now.)
# I include these just to preserve the previous code.
# this particular zip_data_wit

zip_data_with_dummies <- test %>%
  mutate("350_1mil" = ifelse(loan_range == "d $350,000-1 million", 1, 0),
         "150-350" = ifelse(loan_range == "e $150,000-350,000", 1, 0),
         "5mil_10mil" = ifelse(loan_range == "a $5-10 million", 1, 0),
         "2mil_5mil" = ifelse(loan_range == "b $2-5 million", 1, 0),
         "1mil_2mil" = ifelse(loan_range == "c $1-2 million", 1, 0),
         "150_less" = ifelse(loan_range == "less than 150k", 1, 0)
         )
```