---
title: "latest_covid_cases"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(readxl)
library(openintro)
library(zoo)
library(lmtest)
library(sandwich)
library(miceadds)

#ppp_allvars_1024_marital <- readRDS('ppp_allvars_1024_marital.rds')
```


```{r creating covid case counts}
county_zip_crosswalk <- read_excel('raw_data/crosswalks/COUNTY_ZIP_092020.xlsx') %>%
  clean_names() %>%
  select(county, zip, res_ratio)

county_covid <- read_csv('raw_data/covid/us-counties.csv') %>%
  filter(date > as.Date("2020-03-27")) %>%
  select(-county, -state)

weighted_cases_current <- left_join(county_zip_crosswalk, county_covid, by = c("county" = "fips"))
```


```{r creating covid case counts, after cleaning}
weighted_cases_current_2 <- weighted_cases_current %>%
  mutate(weighted_cases = cases * res_ratio,
         weighted_deaths = deaths * res_ratio) %>%
  select(-county, -res_ratio) %>%
  group_by(zip, date) %>%
  summarize(weighted_cases = sum(weighted_cases),
            weighted_deaths = sum(weighted_deaths))

weighted_cases_current_3 <- weighted_cases_current_2 %>%
  filter(date <= as.Date("2020-08-08"), date >= as.Date("2020-03-27"))


# Using distinct is so we don't get a memory overflow here -- it's necessary
dates_approved <- ppp_allvars_1024_marital %>%
  select(zip, date_approved) %>%
  distinct()

# This still often causes a memory overflow :( Run in Rstudio Server if problem

weighted_cases_current_4 <- left_join(dates_approved, weighted_cases_current_3,
                                      by = "zip")

# rolling 7-day average of cases and deaths before the loan approval date

weighted_cases_current_5 <- weighted_cases_current_4 %>%
  group_by(zip, date_approved) %>%
  filter(date <= date_approved, date > (date_approved - 7))

weighted_cases_current_6 <- weighted_cases_current_5 %>%
  summarize(mean_end_cases_weighted = mean(weighted_cases),
            mean_end_deaths_weighted = mean(weighted_deaths), .groups = "drop")
```


```{r merging}

# This was generated in Rstudio server
weighted_cases_current_6 <- read_csv('weighted_cases_current_6.csv')

ppp_allvars_1028 <- left_join(ppp_allvars_1024_marital, weighted_cases_current_6,
                              by = c("zip", "date_approved")) %>%
  drop_na(mean_end_cases_weighted, mean_end_deaths_weighted)

ppp_allvars_1028 <- ppp_allvars_1028 %>%
  mutate(mean_end_cases_weighted = mean_end_cases_weighted * 10000 / population,
         mean_end_deaths_weighted = mean_end_deaths_weighted * 10000 / population)
```

```{r}
# Now we want to include social distancing restrictions by state
state_policies <- read_excel("raw_data/covid/7-30-2020_Social_Distancing.xlsx",
                             sheet = "2020-06-22_Social Distancing Or", skip = 1,
                             col_types = c("guess", "date", "date", "date", "date",
                                           "date", "date", "guess", "date",
                                           "date", "date", "date", "date",
                                           "date")) %>%
  clean_names() %>%
  select(state, stay_at_home_start, non_essential_business_closure_start, 
         stay_at_home_end, 
         non_essential_business_closure_end) %>%
  
  # We just make NAs some later date just so they don't mess up our inequalities
  
  mutate(stay_at_home_start = replace_na(stay_at_home_start, as.Date("2021-01-01")),
         stay_at_home_end = replace_na(stay_at_home_end, as.Date("2021-01-01")),
         non_essential_business_closure_start = 
           replace_na(non_essential_business_closure_start, as.Date("2021-01-01")),
         non_essential_business_closure_end = 
           replace_na(non_essential_business_closure_end, as.Date("2021-01-01"))) %>%
  mutate(stay_at_home_apr = ifelse(stay_at_home_start <= as.Date("2020-04-03"),
                                   1, 0),
         non_essential_closure_apr = 
           ifelse(non_essential_business_closure_start <= as.Date("2020-04-03"),
                  1, 0)) %>%
  mutate(stay_at_home_apr = replace_na(stay_at_home_apr, 0),
         non_essential_closure_apr = replace_na(non_essential_closure_apr, 0))

states <- ppp_allvars_1028 %>%
  select(cd_name, date_approved) %>%
  mutate(state_abb = str_sub(cd_name, 1, 2)) %>%
  mutate(state = abbr2state(state_abb))

states_merged <- left_join(states, state_policies, by = "state") %>%
  mutate(stay_at_home_current = 
           ifelse(stay_at_home_start <= date_approved & 
                    date_approved <= stay_at_home_end,
                  1, 0),
         non_essential_closure_current =  
           ifelse(non_essential_business_closure_start <= date_approved & 
                    date_approved <= non_essential_business_closure_end,
                  1, 0))

states_merged_cleaned <- states_merged %>%
  select(stay_at_home_apr, stay_at_home_current, 
         non_essential_closure_apr, non_essential_closure_current)
```


```{r}
ppp_allvars_1028_lockdowns <- bind_cols(ppp_allvars_1028, states_merged_cleaned)
```


```{r}
# Adding in some COVID-related unemployment data too!

# This is taken from earlier

county_zip_crosswalk <- read_excel('raw_data/crosswalks/COUNTY_ZIP_092020.xlsx') %>%
  clean_names() %>%
  select(county, zip, res_ratio)

unemploy <- read_excel('raw_data/unemployment/laucntycur14.xlsx', skip = 4) %>%
  clean_names() %>%
  select(state_fips_code, county_fips_code, period, 
         unemployed, labor_force, unemployment_rate_percent) %>%
  mutate(fips_code = str_c(state_fips_code, county_fips_code, sep = "")) %>%
  drop_na(fips_code)

# Weight this by population

unemploy_zip <- left_join(county_zip_crosswalk, unemploy,
                          by = c("county" = "fips_code")) %>%
  select(-state_fips_code, -county_fips_code) %>%
  group_by(zip, period) %>%
  mutate(labor_force = labor_force * res_ratio,
         unemployed = unemployed * res_ratio) %>%
  summarize(total_labor = sum(labor_force),
            total_unemployed = sum(unemployed), .groups = "drop") %>%
  mutate(unemployment_rate = total_unemployed * 100 / total_labor) %>%
  filter(period %in% c("Apr-20", "May-20", "Jun-20", "Jul-20", "Aug-20 p"))

unemploy_zip_dates <- unemploy_zip %>%
  mutate(period = ifelse(period == "Aug-20 p", "Aug-20", period)) %>%
  mutate(period = as.Date(paste("01", period, sep="-"), "%d-%b-%y")) %>%
  mutate(month = month(period))
```


```{r}
# Matching months
ppp_months <- ppp_allvars_1028_lockdowns %>%
  mutate(month = month(date_approved))

ppp_allvars_1028_unemploy <- left_join(ppp_months, unemploy_zip_dates, 
                                       by = c("zip", "month"))

unemploy_apr <- unemploy_zip_dates %>%
  filter(month == 4) %>%
  select(-total_labor, -total_unemployed, -period) %>%
  rename("unemployment_rate_apr" = "unemployment_rate")

ppp_allvars_1028_unemploy_2 <- left_join(ppp_allvars_1028_unemploy,
                                         unemploy_apr, by = "zip") %>%
  select(-total_labor, -total_unemployed, -period) %>%
  drop_na(unemployment_rate, unemployment_rate_apr)
```


```{r}
# Adding in gini index
inequality <- read_csv('raw_data/acs_gini/ACSDT5Y2018.B19083_data_with_overlays_2020-10-26T225918.csv',
                       skip = 1) %>%
  clean_names() %>%
  select(geographic_area_name, estimate_gini_index) %>%
  mutate(estimate_gini_index = as.double(estimate_gini_index),
         geographic_area_name = 
           map_chr(geographic_area_name, ~ substring(., 6))) %>%
  mutate(geographic_area_name = str_trim(geographic_area_name, side = "both"))

current <- ppp_allvars_1028_unemploy_2
  #readRDS('ppp_allvars_1024_unemploy.rds')

ppp_allvars_1027 <- left_join(current, inequality, 
                              by = c("zip" = "geographic_area_name")) %>%
  select(-month.y) %>%
  rename("month" = "month.x") %>%
  drop_na(estimate_gini_index)

# ppp_allvars_1027 %>%
#   summarize(mean = mean(estimate_gini_index), sd = sd(estimate_gini_index))
```


```{r}
# Adding in violent crime rates
crime <- read_excel('raw_data/county/county_health.xlsx', sheet = 'Ranked Measure Data',
                    skip = 1) %>%
  clean_names() %>%
  select(fips, annual_average_violent_crimes)

# Don't need to run this again if you have it above

county_zip_crosswalk <- read_excel('raw_data/crosswalks/COUNTY_ZIP_092020.xlsx') %>%
  clean_names() %>%
  select(county, zip, res_ratio)

# Weighting by population

crime_zip <- left_join(county_zip_crosswalk, crime, by = c("county" = "fips")) %>%
  mutate(annual_average_violent_crimes = annual_average_violent_crimes * res_ratio) %>%
  drop_na(annual_average_violent_crimes) %>%
  group_by(zip) %>%
  summarize(total_crime = sum(annual_average_violent_crimes), .groups = "drop")

ppp_allvars_1027_crime <- left_join(ppp_allvars_1027, crime_zip, by = "zip") %>%
  mutate(violent_crime_rate = total_crime * 100000 / population) %>%
  drop_na(violent_crime_rate) %>%
  select(-total_crime)
  
#ppp_allvars_1027_crime %>% summarize(mean = mean(violent_crime_rate), sd = sd(violent_crime_rate))


```


```{r}
ppp_allvars_1027_crime <- readRDS('ppp_allvars_1028.rds')
test_regression <-
  lm(ppp_allvars_1027_crime$days_to_approval ~ 1 + ppp_allvars_1027_crime$median_family_income +
       ppp_allvars_1027_crime$black_percent +
       I(ppp_allvars_1027_crime$black_percent ^ 2) +
       ppp_allvars_1027_crime$white_percent + I(ppp_allvars_1027_crime$white_percent ^ 2) +
       ppp_allvars_1027_crime$high_school_pct +
       ppp_allvars_1027_crime$banks_per_pop + 
       ppp_allvars_1027_crime$loan_350_1mil + ppp_allvars_1027_crime$loan_150_350 + 
       ppp_allvars_1027_crime$loan_5mil_10mil +
       ppp_allvars_1027_crime$loan_2mil_5mil + ppp_allvars_1027_crime$loan_1mil_2mil +
       ppp_allvars_1027_crime$cook_pvi + ppp_allvars_1027_crime$mean_start_cases_weighted + 
       ppp_allvars_1027_crime$mean_start_deaths_weighted + ppp_allvars_1027_crime$mean_end_cases_weighted +
       ppp_allvars_1027_crime$mean_end_deaths_weighted + 
       ppp_allvars_1027_crime$bank_ppp_issued +
       ppp_allvars_1027_crime$rural + ppp_allvars_1027_crime$businesses_per_pop +
       ppp_allvars_1027_crime$married_percent + ppp_allvars_1027_crime$preference +
       ppp_allvars_1027_crime$requirement + 
       ppp_allvars_1027_crime$stay_at_home_apr +
       ppp_allvars_1027_crime$stay_at_home_current +
       ppp_allvars_1027_crime$non_essential_closure_apr +
       ppp_allvars_1027_crime$non_essential_closure_current + 
       ppp_allvars_1027_crime$unemployment_rate + 
       ppp_allvars_1027_crime$unemployment_rate_apr + 
       ppp_allvars_1027_crime$estimate_gini_index +
       ppp_allvars_1027_crime$violent_crime_rate +
       ppp_allvars_1027_crime$jobs_reported +
       
       I(ppp_allvars_1027_crime$black_percent * ppp_allvars_1027_crime$preference) +
       I(ppp_allvars_1027_crime$black_percent * ppp_allvars_1027_crime$requirement) + 
       I(ppp_allvars_1027_crime$black_percent * ppp_allvars_1027_crime$loan_350_1mil) +
       I(ppp_allvars_1027_crime$black_percent * ppp_allvars_1027_crime$loan_150_350) +
       I(ppp_allvars_1027_crime$black_percent * ppp_allvars_1027_crime$loan_1mil_2mil) +
       I(ppp_allvars_1027_crime$black_percent * ppp_allvars_1027_crime$loan_5mil_10mil) +
       I(ppp_allvars_1027_crime$black_percent * ppp_allvars_1027_crime$loan_5mil_10mil))

summary(test_regression)
```


```{r}
zip_regression_hetero <- coeftest(test_regression, vcov = vcovHC(test_regression, type = "HC0", cluster = "group"))

zip_regression_hetero_tibble = tidy(zip_regression_hetero)
```


```{r}
lm.cluster(ppp_allvars_1027_crime, 
           days_to_approval ~ 1 + median_family_income +
       black_percent +
       I(black_percent ^ 2) +
       white_percent + I(white_percent ^ 2) +
       high_school_pct +
       banks_per_pop + 
       loan_350_1mil + loan_150_350 + 
       loan_5mil_10mil +
       loan_2mil_5mil + loan_1mil_2mil +
       cook_pvi + mean_start_cases_weighted + 
       mean_start_deaths_weighted + mean_end_cases_weighted +
       mean_end_deaths_weighted + 
       bank_ppp_issued +
       rural + businesses_per_pop +
       married_percent + preference +
       requirement + 
       stay_at_home_apr +
       stay_at_home_current +
       non_essential_closure_apr +
       non_essential_closure_current + 
       unemployment_rate + 
       unemployment_rate_apr + 
       estimate_gini_index +
       violent_crime_rate +
       jobs_reported +
       
       I(black_percent * preference) +
       I(black_percent * requirement) + 
       I(black_percent * loan_350_1mil) +
       I(black_percent * loan_150_350) +
       I(black_percent * loan_1mil_2mil) +
       I(black_percent * loan_5mil_10mil) +
       I(black_percent * loan_5mil_10mil),
       
       cluster = ppp_allvars_1027_crime$zip)


```

```{r}
ppp_logtest <- ppp_allvars_1020_lockdowns %>%
  mutate(logdays = ifelse(log(days_to_approval) == -Inf, 0, log(days_to_approval))) %>%
  mutate(logbiz = ifelse(log(number_of_establishments) == -Inf, 0, log(number_of_establishments))) %>%
  mutate(logbanks = ifelse(log(banks_per_pop) == -Inf, 0, log(banks_per_pop)))

log_regression_test <- 
    lm(ppp_logtest$logdays ~ 1 + ppp_logtest$median_family_income +
       ppp_logtest$black_percent +
       ppp_logtest$white_percent + ppp_logtest$high_school_pct +
       ppp_logtest$logbanks + 
       ppp_logtest$loan_350_1mil + ppp_logtest$loan_150_350 + 
       ppp_logtest$loan_5mil_10mil +
       ppp_logtest$loan_2mil_5mil + ppp_logtest$loan_1mil_2mil +
       ppp_logtest$cook_pvi + ppp_logtest$mean_start_cases_weighted + 
       ppp_logtest$mean_start_deaths_weighted + ppp_logtest$bank_ppp_issued +
       ppp_logtest$rural + ppp_logtest$logbiz + 
       ppp_logtest$married_percent + ppp_logtest$preference + 
       ppp_logtest$requirement +
       ppp_logtest$stay_at_home_apr +
       ppp_logtest$stay_at_home_current +
       ppp_logtest$non_essential_closure_apr +
       ppp_logtest$non_essential_closure_current +
       
       ppp_logtest$black_percent * ppp_logtest$preference +
       ppp_logtest$black_percent * ppp_logtest$requirement + 
       ppp_logtest$black_percent * ppp_logtest$loan_350_1mil +
       ppp_logtest$black_percent * ppp_logtest$loan_150_350 +
       ppp_logtest$black_percent * ppp_logtest$loan_1mil_2mil +
       ppp_logtest$black_percent * ppp_logtest$loan_5mil_10mil +
       ppp_logtest$black_percent * ppp_logtest$loan_5mil_10mil)
summary(log_regression_test)
```


```{r}
bptest(test_regression)
```

