---
title: "mapping_descriptives"
author: "Justin Qi"
date: "10/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(maps)
library(usmap)
library(readxl)
library(lubridate)
library(gganimate)
library(lfe)
```

```{r getting zip code counts for original}
# Reading in the original loan data, which includes zip (all we need)

original <- readRDS('ppp_loanonly_all_loans.rds') %>%
  select(zip) %>%
  group_by(zip) %>%
  summarize(number = n(), .groups = "drop")
```

```{r new data}
# This uses a slightly older version than our final dataset but the difference
# in the number of loans is pretty negligible.

new <- readRDS('most_recent_zip_nobanks_1118.rds') %>%
  select(zip) %>%
  group_by(zip) %>%
  summarize(number = n(), .groups = "drop")
```


```{r new data 2}
# Testing an older dataset to see what changed

# new2 <- ppp_covidadj %>%
#   #readRDS('ppp_pvi_1017.rds') %>%
#   select(zip) %>%
#   group_by(zip) %>%
#   summarize(number = n(), .groups = "drop")
```


```{r matching up zips and lat/long}
# This converts zip codes to rough lat-long estimates
ziplat <- 
  read_delim('raw_data/crosswalks/us-zip-code-latitude-and-longitude.csv',
                   delim = ";") %>%
  clean_names() %>%
  select(zip, latitude, longitude)

# We convert original loan data and new loan data to zip.

original_lat <- left_join(original, ziplat, by = "zip") %>%
  drop_na(latitude)

new_lat <- left_join(new, ziplat, by = "zip") %>%
  drop_na(latitude)

# new2_late <- left_join(new2, ziplat, by = "zip") %>%
#   drop_na(latitude)

```


```{r graphing}
# Use a US map and then make a heatmap of the loans by zip code. I did this
# using an online tutorial: 
# https://rstudio-pubs-static.s3.amazonaws.com/274683_cd798195cbaf4a7a900cceaafb73ea11.html

us <- map_data('state')

ggplot(original_lat, aes(longitude, latitude)) +
  geom_polygon(data=us,aes(x = long,y = lat, group = group),
               color = 'gray', fill = NA, alpha = .35)+
  geom_point(aes(color = number),size = 1,alpha = 0.07) + 
  theme_void() +
  xlim(-125,-65) + ylim(25,50) +
  theme(axis.title = element_blank(), axis.ticks = element_blank(),
        axis.text = element_blank()) + 
  scale_colour_gradient(high="dark blue", low="light blue",
                        name = "Number of Loans")
```


```{r graphing}
# Similarly we then do this for our final dataset too!

ggplot(new_lat, aes(longitude, latitude)) +
  geom_polygon(data = us, aes(x = long,y = lat, group = group), color = 'gray',
               fill = NA, alpha = .35)+
  geom_point(aes(color = number), size=1, alpha=0.11) + 
  theme_void() +
  xlim(-125, -65) +
  ylim(25, 50) +
  theme(axis.title = element_blank(), axis.ticks = element_blank(),
        axis.text = element_blank(), panel.grid.major = element_blank()) +
  scale_colour_gradient(high = "dark blue", low = "light blue", 
                        breaks = waiver(), n.breaks = 4,
                        limits = c(0, 3000),
                        name = "Number of Loans")
```


```{r graphing}
# ggplot(new2_late, aes(longitude, latitude)) +
#   geom_polygon(data = us, aes(x = long,y = lat, group = group),color='gray',
#                fill = NA, alpha = .35)+
#   geom_point(aes(color = number),size=1,alpha=0.11) + 
#   theme_void() +
#   xlim(-125,-65) +
#   ylim(25,50) +
#   theme(axis.title = element_blank(), axis.ticks = element_blank(),
#         axis.text = element_blank(), panel.grid.major = element_blank()) +
#   scale_colour_gradient(high="dark blue", low="light blue", 
#                         name = "Number of Loans")
```

```{r}
# Let's read in some unemployment data and see what happens -- trying to make
# a county level heatmap

unemploy <- read_excel('raw_data/unemployment/laucntycur14.xlsx', skip = 4) %>%
  clean_names() %>%
  select(state_fips_code, county_fips_code, period, 
         unemployed, labor_force, unemployment_rate_percent) %>%
  mutate(fips_code = str_c(state_fips_code, county_fips_code, sep = "")) %>%
  drop_na(fips_code) %>%
  mutate(period = ifelse(period == "Aug-20 p", "Aug-20", period)) %>%
  mutate(period = as.Date(paste("01", period, sep="-"), "%d-%b-%y")) %>%
  mutate(month = month(period)) %>%
  rename("fips" = "fips_code") %>%
  select(unemployment_rate_percent, fips, month) %>%
  mutate(month = as.integer(month))
```

```{r}
# This is me just setting up the dates properly.

counties <- unemploy %>%
  select(fips) %>%
  distinct()

all <- expand_grid(fips = counties$fips,
                   month = 1:12)

all_unemploy <- left_join(all, unemploy, by = c("fips", "month"))
```

```{r}
# THis is just rough code that I then modify and put into my Shiny app, so it
# doesn't look great and isn't finalized -- just for me to experiment with
# some different settings

unemploy <- unemploy %>%
  mutate(month = as.integer(month))

plot1 <- plot_usmap(regions = "counties", data = unemploy, 
                    values = "unemployment_rate_percent",
             color = NA, include = "HI") + 
  labs(title = "{closest_state}",
       subtitle = "This is a blank map of the counties of the United States.") + 
  theme(panel.background = element_rect(color = "black", fill = "white"),
        legend.position = "right") +
  scale_fill_gradient(high="dark blue", low="light blue",
                        name = "Unemployment Rate",
                        n.breaks = 5)



plot1 + transition_states(month)

# p + transition_time(month)
```

```{r}
# This is me creating a map of minority percent disparities by state using 
# the coefficients on interaction terms -- this is purely experimental, and
# needs the usmap function I think

covid_fe_tidied <- covid %>%
  slice(27:78) %>%
  mutate(state = str_sub(term, 23)) %>%
  drop_na() %>%
  select(state, estimate) %>%
  add_row(state = "AK", estimate = 0)

plot_usmap(regions = "states", data = covid_fe_tidied,
           values = "estimate") +
  theme(panel.background = element_rect(color = "black", fill = "white"),
        legend.position = "right") +
   scale_fill_distiller(type = "seq",
                             palette = "Blues",
                             na.value = "grey50",
                             direction = 1,
                             name = "Interaction Coefficient",
                             n.breaks = 5) +
  labs(title = "Racial Disparities in Lending by State",
       subtitle = "Values are coefficients of interaction terms (log-scaled business days regressed on race).") +
  guides(fill = guide_colourbar(frame.colour = "black",
                                      ticks.colour = "black"))
```
```{r}

# Adding yet another map -- bank loans by location for the Business
# Roundtable banks

most_recent <- readRDS('most_recent_zip_nobanks_1130.rds') %>%
  mutate(lender = tolower(lender)) %>%
  mutate(lender = as.factor(lender)) %>%
  select(zip, lender) %>%
  group_by(zip, lender) %>%
  summarize(number = n(), .groups = "drop") %>%
  filter(lender %in% c("bank of america, national association",
                        "citibank, n.a.",
                        "keybank national association",
                        "jpmorgan chase bank, national association",
                        "wells fargo bank, national association"))


ziplat <- 
  read_delim('raw_data/crosswalks/us-zip-code-latitude-and-longitude.csv',
                   delim = ";") %>%
  clean_names() %>%
  select(zip, latitude, longitude)

new_lat <- left_join(most_recent, ziplat, by = "zip") %>%
  drop_na(latitude) %>%
  mutate(lender = as.character(lender)) %>%
  mutate(lender = ifelse(lender == "bank of america, national association",
                         "Bank of America", lender)) %>%
  mutate(lender = ifelse(lender == "citibank, n.a.",
                         "Citibank", lender)) %>%
  mutate(lender = ifelse(lender == "keybank national association",
                         "KeyBank", lender)) %>%
  mutate(lender = ifelse(lender == "jpmorgan chase bank, national association",
                         "JPMorgan Chase", lender)) %>%
  mutate(lender = ifelse(lender == "wells fargo bank, national association",
                         "Wells Fargo", lender)) %>%
  mutate(lender = as.factor(lender))
```

```{r}
us <- map_data('state')

ggplot(new_lat, aes(longitude, latitude)) +
  geom_polygon(data=us,aes(x = long,y = lat, group = group),
               color = 'gray', fill = NA, alpha = .35) +
  geom_point(aes(color = number),size = 1,alpha = 0.07) +
  xlim(-125,-65) + ylim(25,50) +
  theme_linedraw() +
  theme(axis.ticks = element_blank(),
        axis.line = element_blank(), 
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = c(0.85, 0.25),
        legend.background = element_rect(colour = "black")) +
  scale_color_gradient(low = "dodgerblue", high = "dodgerblue4",
                        name = "Number of Loans",
                        n.breaks = 4,
                      breaks = waiver(),
                      limits = c(0, 600)) +
  guides(color = guide_colourbar(frame.colour = "black",
                                      ticks.colour = "black")) +
  facet_wrap(~ lender)
```
```{r}
# Let's try mapping Business Roundtable by state as well

most_recent <- readRDS('most_recent_zip_1130.rds') %>%
  mutate(national = 0) %>%
  mutate(national = ifelse(str_detect(lender, pattern = "national association"),
                           1, national),
         national = ifelse(str_detect(lender, pattern = "n.a."),
                           1, national)) %>%
  mutate(cu = 0) %>%
  mutate(cu = ifelse(str_detect(lender, pattern = "\\sfcu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "\\scu$"), 1, 
                              cu),
         cu = ifelse(str_detect(lender, pattern = "credit union"), 1, 
                              cu)) %>%
  mutate(business_roundtable = ifelse(lender %in%
                                        c("bank of america, national association",
                                          "citibank, n.a.",
                                          "keybank national association",
                                          "jpmorgan chase bank, national association",
                                          "wells fargo bank, national association"),
                                      1, 0)) %>%
  mutate(state = as.factor(state), zip = as.factor(zip),
         log_days = log(business_days + 1))
  
roundtable_reg <- felm(
    log_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent +
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + renter_percent +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
       national + cu + business_roundtable +
    I(national * minority_percent) + 
    I(business_roundtable * minority_percent) + 
    state:minority_percent:business_roundtable + 
    state:minority_percent|state|0|zip, 
    data = most_recent)

roundtable <- tidy(roundtable_reg)

```
```{r}
roundtable_clean <- roundtable %>%
  slice(90:141) %>%
  drop_na(estimate) %>%
  mutate(state = str_sub(term, 43)) %>%
  select(-term) %>%
  select(estimate, state)

plot_usmap(regions = "states", data = roundtable_clean,
           values = "estimate") +
  theme(panel.background = element_rect(color = "black", fill = "white"),
        legend.position = "right") +
   scale_fill_distiller(type = "seq",
                             palette = "YlGnBu",
                             na.value = "grey50",
                             direction = 1,
                             name = "Interaction Coefficient",
                             n.breaks = 5) +
  labs(title = "Business Roundtable Effect by State",
       subtitle = "Values are coefficients of interaction terms (log-scaled business days regressed on signatory status).") +
  guides(fill = guide_colourbar(frame.colour = "black",
                                      ticks.colour = "black"))

```

