---
title: "counties"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
library(openintro)
library(broom)
library(lmtest)
library(sandwich)
library(bizdays)

#loan_only <- readRDS('ppp_loanonly_all_loans.rds')

# For robustness we needed to make sure that county-level regressions hold too.
# Again, this is a minor (if at all) part of my Gov 50 work and mostly for
# the other classes that I'm working on, so feel free to ignore this one too.
# Most of this is identical to files 1-5 except consolidated in one file
# and with slightly different data sources on the county level.
```


```{r}
# Loan data has to include jobs -- we remake the loan only dataset, though
# this isn't needed anymore since I've made an RDS with this.

ppp_150 <- read_csv("raw_data/sba/PPP_SBA_150.csv") %>%
  clean_names() %>%
  select(loan_range, zip, date_approved, lender, address, city, state, jobs_reported) %>%
  drop_na(zip) %>%
  
  # This calculates the date on which loans were approved vs. when apps opened.
  # now deprecated b/c I moved to using bizdays instead
  
  mutate(date_approved = mdy(date_approved), 
         days_to_approval = date_approved - mdy("04/03/2020"),
         zip = as.character(zip))


sba_cleaning <- function(file) {
  x <- read_csv(file) %>%
    clean_names() %>%
    select(loan_amount, zip, date_approved, 
           lender, city, state, jobs_reported) %>%
    drop_na(zip) %>%
    mutate(date_approved = mdy(date_approved), 
         days_to_approval = date_approved - mdy("04/03/2020"),
         zip = as.character(zip))
}

# run for Mac

file.names1 <- 
  dir(path = "/Users/Regular/Desktop/GOV50/pppdata/raw_data/sba/states/", 
      pattern = ".csv")

# run for Windows

file.names2 <- 
  dir(path = "C:/Justin/Gov50/pppdata/raw_data/sba/states/", pattern = ".csv")

all_states<- tibble()

for(i in 1:length(file.names2)) {
  file <- sba_cleaning(paste("raw_data/sba/states/",file.names2[i], sep = ""))
  all_states <- rbind(all_states, file)
}

all_states2 <- all_states %>%
  mutate(loan_range = "less than 150k", address = NA)

ppp_150_newcol <- ppp_150 %>%
  mutate(loan_amount = NA) %>%
  mutate(loan_amount = as.character(loan_amount))

loan_only <- rbind(ppp_150_newcol, all_states2) %>%
  
loan_only <- loan_only %>%
  drop_na(jobs_reported)
```

```{r}
loan_only <- readRDS('ppp_loanonly_with_jobs.rds')
```

```{r}

# Starting on reading in demographic data

educ <- read_csv('raw_data/county/county_edu.csv', skip = 1) %>%
  clean_names()

hs_id <- educ %>%
  select(id, geographic_area_name,
         estimate_percent_population_25_years_and_over_population_35_to_44_years_high_school_graduate_or_higher)
```


```{r}
# This is household median income

income <- read_csv('raw_data/county/county_income.csv', skip = 1) %>%
  clean_names() %>%
  select(id, geographic_area_name, estimate_households_median_income_dollars) %>%
  mutate(geographic_area_name = map_chr(geographic_area_name, ~ substring(., 6)),
         estimate_households_median_income_dollars = 
           as.double(estimate_households_median_income_dollars))

marital <- read_csv('raw_data/county/county_marital.csv', skip = 1) %>%
  clean_names() %>%
  select(id, geographic_area_name, 
         estimate_now_married_except_separated_population_15_years_and_over) %>%
  mutate(estimate_now_married_except_separated_population_15_years_and_over = 
           as.double(estimate_now_married_except_separated_population_15_years_and_over))
```


```{r}
race <- read_csv('raw_data/county/county_race.csv', skip = 1) %>%
  clean_names() %>%
  select(id, geographic_area_name, estimate_total, estimate_total_white_alone,
         estimate_total_black_or_african_american_alone) %>%
  mutate(black_percent = 
           estimate_total_black_or_african_american_alone / estimate_total,
         white_percent = 
          estimate_total_white_alone / estimate_total ) %>%
  select(-estimate_total_white_alone, 
         -estimate_total_black_or_african_american_alone)
```


```{r}
businesses <- read_csv('raw_data/county/CBP2016.CB1600CBP_data_with_overlays_2020-10-16T114119.csv',
                       skip = 1) %>%
  clean_names() %>%
  filter(meaning_of_employment_size_of_establishments == "All establishments",
         meaning_of_legal_form_of_organization_code == "All establishments") %>%
  select(id, geographic_area_name, number_of_establishments) %>%
  
  # Terrible practice but I'm just slicing the rows where I 
  # know total business counts are lol
  
  slice(1:3304)
```


```{r}
merge1 <- inner_join(hs_id, income, by = "id")

merge2 <- inner_join(merge1, marital, by = "id")

merge3 <- inner_join(merge2, race, by = "id")

merge4 <- left_join(merge3, businesses, by = "id") %>%
  select(-geographic_area_name.x, -geographic_area_name.y, -geographic_area_name.x.x,
         -geographic_area_name.y.y, -geographic_area_name) %>%
  mutate(businesses_per_pop = number_of_establishments / estimate_total) %>%
  rename("married_percent" = "estimate_now_married_except_separated_population_15_years_and_over",
         "median_income" = "estimate_households_median_income_dollars") %>%
  select(-number_of_establishments)
```


```{r}

# Elections data -- this replaces cook pvi on county level

elections <- read_csv('raw_data/county_elections/countypres_2000-2016.csv') %>%
  clean_names() %>%
  filter(year == "2016")

elections_clean <- elections %>%
  select(fips, party, candidatevotes, totalvotes) %>%
  group_by(fips, party) %>%
  summarize(percent = candidatevotes/totalvotes, .groups = "drop") %>%
  filter(party == "republican") %>%
  mutate(percent = percent * 100, 
         fips = str_pad(fips, width = 5, "left", "0")) %>%
  select(-party)
```


```{r}
demographics <- merge4 %>%
  mutate(fips = map_chr(id, ~ substring(., 10)))

merge5 <- left_join(demographics, elections_clean, by = "fips") %>%
  drop_na(percent)
```


```{r}
# Merging everything and assigning fips county codes to the zip-level
# loan data

county_zip_crosswalk <- 
  read_excel('raw_data/crosswalks/COUNTY_ZIP_092020.xlsx') %>%
  clean_names() %>%
  select(county, zip, res_ratio) %>%
  group_by(zip) %>%
  arrange(desc(res_ratio)) %>%
  slice(1) %>%
  select(-res_ratio)

loan_only_fips <- left_join(loan_only, county_zip_crosswalk, by = "zip") %>%
  drop_na(county) %>%
  rename('fips' = 'county')

combined <- left_join(loan_only_fips, merge5, by = "fips") %>%
  rename('high_school_pct' = 'estimate_percent_population_25_years_and_over_population_35_to_44_years_high_school_graduate_or_higher', 'republican_percent' = 'percent') %>%
  drop_na(high_school_pct, median_income, married_percent, estimate_total, black_percent,
          white_percent, businesses_per_pop, republican_percent)
```


```{r}

# Merge in bank population values

banks <- read_csv("raw_data/fdic/OFFICES2_PART2.csv", col_types = cols(
  'ZIP' = col_character()))%>%
  clean_names() %>%
  select(zip)

# cbsa_crosswalk <- read_csv('raw_data/crosswalks/cbsa2fipsxw.csv') %>%
#   clean_names() %>%
#   select(cbsacode, fipsstatecode, fipscountycode, centraloutlyingcounty) %>%
#   mutate(number_zero =
#            5 - str_length(fipsstatecode)) %>%
#   mutate(fipscountycode = str_pad(fipscountycode, width = number_zero,
#                                   "left", "0")) %>%
#   mutate(fipsfull = str_c(fipsstatecode, fipscountycode, sep = "")) %>%
#   filter(centraloutlyingcounty == "Central")

banks_matched <- left_join(banks, county_zip_crosswalk, by = "zip") %>%
  drop_na(county) %>%
  select(-zip) %>%
  group_by(county) %>%
  summarize(number_banks = n())

combined_with_bank <- left_join(combined, banks_matched, 
                                by = c("fips" = "county")) %>%
  mutate(number_banks = replace_na(number_banks, 0)) %>%
  mutate(banks_per_pop = number_banks * 10000 / estimate_total) %>%
  select(-number_banks)
```


```{r}

# Merge in premade population density file

pop_density <- read_csv('raw_data/county/census-population-landarea.csv') %>%
  clean_names() %>%
  select(fips, 'pop060210') %>%
  mutate(fips = str_pad(fips, width = 5, "left", "0"))

combined_with_popden <- left_join(combined_with_bank, pop_density, by = "fips") %>%
  drop_na('pop060210') %>%
  rename('pop_den' = 'pop060210')
```


```{r}
# covid cases, covid deaths, state requirements, unemployment, loan reqs

county_covid <- read_csv('raw_data/covid/us-counties.csv') %>%
  filter(date > as.Date("2020-03-27")) %>%
  select(date, fips, cases, deaths)

current_cases <- county_covid %>%
  filter(date <= as.Date("2020-04-03")) %>%
  group_by(fips) %>%
  summarize(cases = mean(cases), deaths = mean(deaths), .groups = "drop")

combined_covid_curr <- left_join(combined_with_popden, current_cases, by = "fips") %>%
  mutate(mean_start_cases = cases * 10000/estimate_total,
         mean_start_deaths = deaths * 10000/estimate_total) %>%
  select(-cases, -deaths) %>%
  drop_na(mean_start_cases, mean_start_deaths)
```


```{r}

# Put in COVID case/death rates the week the loan was approved

dates_approved <- combined_covid_curr %>%
  select(date_approved, fips) %>%
  distinct()

temp <- left_join(dates_approved, county_covid, by = "fips") %>%
  filter(date >= date_approved - 6, date <= date_approved) %>%
  group_by(fips) %>%
  summarize(mean_end_cases = mean(cases), mean_end_deaths = mean(deaths))
```


```{r}

# Merging this w/ original loan file (to save memory)

combined_covid <- left_join(combined_covid_curr, temp, by = "fips") %>%
  drop_na(mean_end_cases, mean_end_deaths) %>%
  mutate(mean_end_cases = mean_end_cases * 10000/estimate_total, 
         mean_end_deaths = mean_end_deaths * 10000/estimate_total)
```


```{r}
combined_covid_2 <- combined_covid %>%
    mutate("loan_350_1mil" = ifelse(loan_range == "d $350,000-1 million", 1, 0),
         "loan_150_350" = ifelse(loan_range == "e $150,000-350,000", 1, 0),
         "loan_5mil_10mil" = ifelse(loan_range == "a $5-10 million", 1, 0),
         "loan_2mil_5mil" = ifelse(loan_range == "b $2-5 million", 1, 0),
         "loan_1mil_2mil" = ifelse(loan_range == "c $1-2 million", 1, 0),
         "loan_150_less" = ifelse(loan_range == "less than 150k", 1, 0)
         )
```


```{r}

# Adding in unemployment data

unemploy <- read_excel('raw_data/unemployment/laucntycur14.xlsx', skip = 4) %>%
  clean_names() %>%
  select(state_fips_code, county_fips_code, period, 
         unemployed, labor_force, unemployment_rate_percent) %>%
  mutate(fips_code = str_c(state_fips_code, county_fips_code, sep = "")) %>%
  drop_na(fips_code) %>%
  filter(period %in% c("Apr-20", "May-20", "Jun-20", "Jul-20", "Aug-20 p")) %>%
  mutate(period = ifelse(period == "Aug-20 p", "Aug-20", period)) %>%
  mutate(period = as.Date(paste("01", period, sep="-"), "%d-%b-%y")) %>%
  mutate(month = month(period))

ppp_months <- combined_covid_2 %>%
  mutate(month = month(date_approved))

combined_unemploy <- left_join(ppp_months, unemploy, 
                                       by = c("fips" = "fips_code", "month"))

unemploy_apr <- unemploy %>%
  filter(month == 4) %>%
  select(-period, -unemployed, -labor_force, -state_fips_code,
         -county_fips_code) %>%
  rename("unemployment_rate_apr" = "unemployment_rate_percent")

combined_unemploy2 <- left_join(combined_unemploy,
                                         unemploy_apr, by = c("fips" = "fips_code")) %>%
  drop_na(unemployment_rate_percent, unemployment_rate_apr) %>%
  select(-period, -unemployed, -labor_force, -state_fips_code,
         -county_fips_code)
```


```{r}
# Still need state reqs and loan regs, number of loans per bank

so_far <- combined_unemploy2

  #readRDS('counties_unemploy.rds')

state_policies <- read_excel("raw_data/covid/7-30-2020_Social_Distancing.xlsx",
                             sheet = "2020-06-22_Social Distancing Or", skip = 1,
                             col_types = c("guess", "date", "date", "date", "date",
                                           "date", "date", "guess", "date",
                                           "date", "date", "date", "date",
                                           "date")) %>%
  clean_names() %>%
  select(state, stay_at_home_start, non_essential_business_closure_start, 
         stay_at_home_end, 
         non_essential_business_closure_end) %>%
  
  # We just make NAs some later date just so they don't mess up our inequalities
  
  mutate(stay_at_home_start = replace_na(stay_at_home_start, 
                                         as.Date("2021-01-01")),
         stay_at_home_end = replace_na(stay_at_home_end, 
                                       as.Date("2021-01-01")),
         non_essential_business_closure_start = 
           replace_na(non_essential_business_closure_start, 
                      as.Date("2021-01-01")),
         non_essential_business_closure_end = 
           replace_na(non_essential_business_closure_end, 
                      as.Date("2021-01-01"))) %>%
  mutate(stay_at_home_apr = ifelse(stay_at_home_start <= as.Date("2020-04-03"),
                                   1, 0),
         non_essential_closure_apr = 
           ifelse(non_essential_business_closure_start <= as.Date("2020-04-03"),
                  1, 0)) %>%
  mutate(stay_at_home_apr = replace_na(stay_at_home_apr, 0),
         non_essential_closure_apr = replace_na(non_essential_closure_apr, 0))


prepping_state_policies <- so_far %>%
  mutate(state_name = abbr2state(state)) %>%
  drop_na(state_name) %>%
  select(-month.y) %>%
  rename("month" = "month.x")

states_merged <- left_join(prepping_state_policies, state_policies, 
                           by = c("state_name" = "state")) %>%
    mutate(stay_at_home_current = 
           ifelse(stay_at_home_start <= date_approved & 
                    date_approved <= stay_at_home_end,
                  1, 0),
         non_essential_closure_current =  
           ifelse(non_essential_business_closure_start <= date_approved & 
                    date_approved <= non_essential_business_closure_end,
                  1, 0)) %>%
  select(-stay_at_home_start, -stay_at_home_end, 
         -non_essential_business_closure_start,
         -non_essential_business_closure_end) %>%
  mutate(lender = tolower(lender), lender = str_trim(lender, side = "both"))
```


```{r}
bank_ppp_policy_manual <- 
  read_excel('raw_data/bank_ppp_policy_manual.xlsx', sheet = "Sheet2") %>%
  mutate(sba_name = tolower(sba_name)) %>%
  mutate(sba_name = str_trim(sba_name, side = "both")) %>%
  drop_na(preference, requirement)

banking_policies <- left_join(states_merged, bank_ppp_policy_manual,
                                      by = c("lender" = "sba_name")) %>%
  mutate(requirement = ifelse(str_detect(lender, pattern = "\\sfcu$"), 
                              1, requirement),
         requirement = ifelse(str_detect(lender, pattern = "\\scu$"), 
                              1, requirement),
         requirement = ifelse(str_detect(lender, pattern = "credit union"), 
                              1, requirement)) %>%
  drop_na(requirement) %>%
  mutate(preference = replace_na(preference, 0))

loan_only2 <- readRDS('ppp_loanonly_all_loans.rds')

loan_numbers <- loan_only2 %>%
  select(lender) %>%
  group_by(lender) %>%
  summarize(bank_ppp_issued = n(), .groups = "drop") %>%
  mutate(lender = tolower(lender))

loan_numbers <- 
  left_join(banking_policies, loan_numbers, by = "lender")

loan_numbers2 <- loan_numbers %>%
  select(-bank_name)

loan_numbers2 <- loan_numbers2 %>%
  mutate(days_to_approval = as.double(days_to_approval))
```


```{r}
gini <- read_csv('raw_data/county/county_inequality.csv', skip = 1) %>%
  clean_names() %>%
  select(id, estimate_gini_index) %>%
  mutate(estimate_gini_index = as.double(estimate_gini_index))

income_inequality <- left_join(loan_numbers2, gini, by = "id") %>%
  drop_na(estimate_gini_index)
```


```{r}
# Crime rates

crime <- read_excel('raw_data/county/county_health.xlsx', 
                    sheet = 'Ranked Measure Data',
                    skip = 1) %>%
  clean_names() %>%
  select(fips, violent_crime_rate)

county_crime <- left_join(income_inequality, crime, by = "fips") %>%
  drop_na(violent_crime_rate)
```

```{r}
# If you ran this continuously you'd add this to county crime

county_crime <- readRDS('counties_all_1028.rds.')

gdp <- read_csv('raw_data/gdp/CAGDP2__ALL_AREAS_2001_2018.csv') %>%
  clean_names() %>%
  filter(industry_classification == "All industry total") %>%
  select(geo_fips, x2017) %>%
  mutate(fips = str_sub(geo_fips, 1, 5),
         x2017 = as.double(x2017)) %>%
  rename("gdp" = "x2017")

county_gdp <- left_join(county_crime, gdp, by = "fips") %>%
  drop_na(gdp) %>%
  select(-geo_fips)
```


```{r}

most_recent_county <- readRDS('most_recent_county_1114.rds')

# Trying to add gender data because we forgot it last time

gender <- 
  read_csv('raw_data/county/ACSDP5Y2018.DP05_data_with_overlays_2020-11-12T203338.csv', 
           skip = 1) %>%
  clean_names() %>%
  select(id,
         percent_estimate_citizen_voting_age_population_citizen_18_and_over_population_male) %>%
  rename("male_percent" =
           "percent_estimate_citizen_voting_age_population_citizen_18_and_over_population_male") %>%
  mutate(male_percent = as.double(male_percent)) %>%
  mutate(fips = map_chr(id, ~ substring(., 10))) %>%
  select(-id)

most_recent_county_2 <- left_join(county_gdp, gender, by = "fips") %>%
  drop_na(male_percent)
```

```{r}
# Integrating the transformations I did in the ols_updated file here too --
# just variable fransmorations and business days calculations to make the
# coefficients a little easier to interpret

cal <- create.calendar(name = "mycal", weekdays=c("saturday", "sunday"))

most_recent_county <- most_recent_county_2 %>%
 mutate(median_income = median_income / 1000,
         
         # This is b/c we didn't do per 10,000 people before, but we want 
         # hundreds of businesses 
         # per 10,000 people, or 100
         
         businesses_per_pop = businesses_per_pop * 100,
         violent_crime_rate = violent_crime_rate / 10,
         pop_den = pop_den / 100,
         black_percent = black_percent * 100,
         white_percent = white_percent * 100,
         gdp = gdp / 1000) %>%
  mutate(delay = ifelse(date_approved > as.Date("2020-04-16"), 1, 0),
         business_days = bizdays(as.Date("2020-04-03"), date_approved, 
                                 'mycal')) %>%
  mutate(minority_percent = 100 - white_percent) %>%
  select(-black_percent) %>%
  mutate(fips = as.factor(fips))
```

```{r}
# Let's try adding in minority business ownership as an outcome variable instead

most_recent_county <- readRDS('most_recent_county_nobanks_1130.rds')

most_recent_county <- readRDS('most_recent_county_1130.rds')

ownership <- 
  read_csv('raw_data/county/ABSCS2017.AB1700CSA01_data_with_overlays_2020-12-01T000046.csv',
           skip = 1, col_types = cols()) %>%
  clean_names() %>%
  filter(meaning_of_sex_code == "Total",
         meaning_of_race_code %in% c("Total", "Minority"),
         meaning_of_veteran_code == "Total",
         meaning_of_naics_code == "Total for all sectors",
         meaning_of_ethnicity_code == "Total") %>%
  select(id, meaning_of_race_code, number_of_employer_firms) %>%
  pivot_wider(id_cols = id, names_from = meaning_of_race_code,
              values_from = number_of_employer_firms) %>%
  mutate(Total = as.double(Total),
         Minority = as.double(Minority)) %>%
  drop_na(Total, Minority) %>%
  mutate(percent_minority_biz = Minority * 100 / Total,
         fips = str_sub(id, 10)) %>%
  select(-Total, -Minority, -id)

most_recent_ownership <- 
  left_join(most_recent_county, ownership, by = "fips") %>%
  drop_na(percent_minority_biz)
```

