---
title: "9_new_regressions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lfe)
library(fixest)
library(tidyverse)
library(texreg)
library(readxl)
library(janitor)
```

```{r}

# Reading in actual recent data

most_recent <- readRDS('most_recent_zip_nobanks_1118.rds') %>%
  mutate(log_days = log(business_days + 1)) %>%
  mutate(fips = as.factor(fips), lender = as.factor(lender))

most_recent_county <- readRDS('most_recent_county_nobanks_1118.rds') %>%
  mutate(lender = as.factor(lender))

# Reading most_recent_both later

```

```{r}
# most_recent <- readRDS('most_recent_zip_1117.rds')

# Adding in FIPS to county

most_recent <- readRDS('most_recent_zip_1117.rds')

# most_recent <- readRDS('most_recent_zip_nobanks_1118.rds')

zip_county_crosswalk <- 
  read_excel('raw_data/crosswalks/ZIP_COUNTY_092020.xlsx') %>%
  clean_names() %>%
  select(zip, county, res_ratio) %>%
  group_by(zip) %>%
  arrange(desc(res_ratio)) %>%
  slice(1) %>%
  ungroup() %>%
  select(-res_ratio) %>%
  rename("fips" = "county")

most_recent_2 <- left_join(most_recent, zip_county_crosswalk, by = "zip")
```


```{r}
# adding in county level data to the ZIP for robustness check -- this has all
# been done already so scroll down to the regressions

# Crime

crime <- read_excel('raw_data/county/county_health.xlsx', sheet = 'Ranked Measure Data',
                    skip = 1) %>%
  clean_names() %>%
  rename("county_crime_rate" = "violent_crime_rate") %>%
  select(fips, county_crime_rate)

ppp_crime <- left_join(most_recent, crime, by = "fips") %>%
  drop_na(county_crime_rate)

# unemployment

unemploy <- read_excel('raw_data/unemployment/laucntycur14.xlsx', skip = 4) %>%
  clean_names() %>%
  select(state_fips_code, county_fips_code, period, 
         unemployed, labor_force, unemployment_rate_percent) %>%
  mutate(fips_code = str_c(state_fips_code, county_fips_code, sep = "")) %>%
  drop_na(fips_code) %>%
  filter(period %in% c("Apr-20", "May-20", "Jun-20", "Jul-20", "Aug-20 p")) %>%
  mutate(period = ifelse(period == "Aug-20 p", "Aug-20", period)) %>%
  mutate(period = as.Date(paste("01", period, sep="-"), "%d-%b-%y")) %>%
  mutate(month = month(period)) %>%
  rename("county_unemployment_rate" = "unemployment_rate_percent")

ppp_months <- ppp_crime %>%
  mutate(month = month(date_approved))

combined_unemploy <- left_join(ppp_months, unemploy, 
                                       by = c("fips" = "fips_code", "month"))

unemploy_apr <- unemploy %>%
  filter(month == 4) %>%
  select(-period, -unemployed, -labor_force, -state_fips_code,
         -county_fips_code) %>%
  rename("county_unemployment_rate_apr" = "county_unemployment_rate")

combined_unemploy2 <- left_join(combined_unemploy,
                                         unemploy_apr, 
                                by = c("fips" = "fips_code")) %>%
  drop_na(county_unemployment_rate, county_unemployment_rate_apr) %>%
  select(-period, -unemployed, -labor_force, -state_fips_code,
         -county_fips_code)

```

```{r}
# covid -- app open

county_covid <- read_csv('raw_data/covid/us-counties.csv') %>%
  filter(date > as.Date("2020-03-27")) %>%
  select(date, fips, cases, deaths)

current_cases <- county_covid %>%
  filter(date <= as.Date("2020-04-03")) %>%
  group_by(fips) %>%
  summarize(cases = mean(cases), deaths = mean(deaths), .groups = "drop")

combined_covid_curr <- left_join(combined_unemploy2, current_cases, by = "fips") %>%
  mutate(mean_start_cases = cases * 10000/population,
         mean_start_deaths = deaths * 10000/population) %>%
  select(-cases, -deaths) %>%
  drop_na(mean_start_cases, mean_start_deaths)

dates_approved <- combined_covid_curr %>%
  select(date_approved, fips) %>%
  distinct()

temp <- left_join(dates_approved, county_covid, by = "fips") %>%
  filter(date >= date_approved - 6, date <= date_approved) %>%
  group_by(fips) %>%
  summarize(mean_end_cases = mean(cases), mean_end_deaths = mean(deaths),
            .groups = "drop")

combined_covid <- left_join(combined_covid_curr, temp, by = "fips") %>%
  drop_na(mean_end_cases, mean_end_deaths) %>%
  mutate(mean_end_cases = mean_end_cases * 10000/population, 
         mean_end_deaths = mean_end_deaths * 10000/population)

```


```{r}
# Zip with fixed effects

# Regression 1

demographics <- felm(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate|0|0|zip, data = most_recent)

# Regression 2: Demographics and Loan-Specific

loan_spec <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported|lender|0|zip, data = most_recent)

# Regression 3: economics

econ <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    delay +
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate|lender|0|zip, data = most_recent)

# Regression 4: COVID 

covid <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current|lender|0|zip,
  data = most_recent)

# Take out state clustering here if necessary -- update 11/24 taken out

covid_fe <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current|fips + lender|0|zip,
  data = most_recent)

# Regression 5: Squared

sq <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2)|fips + lender|0|zip,
  data = most_recent)

# Regression 6: interactions

interactions <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2) + 
    I(minority_percent * median_family_income) +
    I(minority_percent * cook_pvi) +
    I(minority_percent * rural) + 
    I(minority_percent * estimate_gini_index) +
    I(minority_percent * violent_crime_rate)|fips + lender|0|zip,
  data = most_recent)

```

```{r}


# county data

most_recent_both <- readRDS('most_recent_zip_withcounties_nobanks_1118.rds') %>%
  mutate(zip = as.factor(zip), fips = as.factor(fips))

# Robustness check -- rerunning regressions with the lovely local data

demographics_check <- felm(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate|0|0|zip + fips, data = most_recent_both)

# Regression 2: Demographics and Loan-Specific

loan_spec_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported|lender|0|zip + fips, data = most_recent_both)

# Regression 3: economics

econ_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    delay +
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate|lender|0|zip + fips, data = most_recent_both)

# Regression 4: COVID 

covid_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current|lender|0|zip + fips,
  data = most_recent_both)

# Regression 5: squared

sq_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2)|lender|0|zip + fips,
  data = most_recent_both)

# Regression 6: interactions

interactions_check <- felm(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    county_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    county_unemployment_rate_apr + 
    county_unemployment_rate + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2) + 
    I(minority_percent * median_family_income) +
    I(minority_percent * cook_pvi) +
    I(minority_percent * rural) + 
    I(minority_percent * estimate_gini_index) +
    I(minority_percent * county_crime_rate)|lender|0|zip + fips,
  data = most_recent_both)
```


```{r}

# County fixed effects on lender

# most_recent_county <- most_recent_county %>%
#   mutate(lender = as.factor(lender))

county_dems <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate|0|0|fips, 
    data = most_recent_county
)

county_loan <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported|lender|0|fips, 
    data = most_recent_county
)

county_econ <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent|lender|0|fips, 
    data = most_recent_county
)

county_covid <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent +
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current|lender|0|fips, 
    data = most_recent_county
)

county_sq <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent +
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2)|lender|0|fips, 
    data = most_recent_county
)


county_interactions <- felm(business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + male_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate +
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent +
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2) + 
    I(minority_percent * median_income) +
    I(minority_percent * republican_percent) +
    I(minority_percent * pop_den) + 
    I(minority_percent * estimate_gini_index) +
    I(minority_percent * violent_crime_rate)|lender|0|fips, 
    data = most_recent_county
)



```

```{r}

# Negative binomial on Zip -- zero inflated negbin from the pscl library

# dems_binomial <- zeroinfl(business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent + 
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     violent_crime_rate,
#     data = most_recent, dist = "negbin")
# 
# 
# loan_binomial <- glm.nb(business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent + 
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     violent_crime_rate +
#     delay + 
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement + 
#     national +
#     cu +
#     bank_ppp_issued + 
#     jobs_reported,
#     data = most_recent)
# 
# econ_binomial <- glm.nb(business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent + 
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     violent_crime_rate +
#     delay + 
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement + 
#     national +
#     cu +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     unemployment_rate_apr + 
#     unemployment_rate,
#     data = most_recent)
# 
# covid_binomial <- glm.nb(business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent + 
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     violent_crime_rate +
#     delay + 
#     loan_150_350 +
#     loan_350_1mil +
#     loan_1mil_2mil +
#     loan_2mil_5mil + 
#     loan_5mil_10mil + 
#     preference + 
#     requirement + 
#     national +
#     cu +
#     bank_ppp_issued + 
#     jobs_reported +
#     banks_per_pop + 
#     businesses_per_pop + 
#     payroll +
#     unemployment_rate_apr + 
#     unemployment_rate +
#     mean_start_cases_weighted +
#     mean_start_deaths_weighted + 
#     mean_end_cases_weighted +
#     mean_end_deaths_weighted,
#     data = most_recent)
```
```{r}
# Trying another way of doing negative binomial w/ fixed effects

dems_binomial <- fenegbin(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate|fips, most_recent)


loan_binomial <- fenegbin(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate +
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported|lender + fips, most_recent)

econ_binomial <- fenegbin(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate +
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported + 
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate|lender + fips, most_recent)

covid_binomial <-  fenegbin(business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate +
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported + 
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate +
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current|lender + fips, most_recent)
```
```{r}
# Trying log again just to see what will happen

# Regression 1

log_demographics <- felm(log_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate|0|0|zip, data = most_recent)

# Regression 2: Demographics and Loan-Specific

log_loan_spec <- felm(
  log_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported|lender|0|zip, data = most_recent)

# Regression 3: economics

log_econ <- felm(
  log_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    delay +
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate|lender|0|zip, data = most_recent)


log_covid_1 <- felm(log_days ~ 
                    1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate +
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported + 
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate +
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current|lender|0|zip, data = most_recent)

log_covid_2 <- felm(log_days ~ 
                    1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate +
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported + 
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate +
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current|lender + fips|0|zip, data = most_recent)

log_interactions_test <- felm(log_days ~ 
                    1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate +
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported + 
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate +
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
      I(minority_percent^2)|lender + fips|0|zip, data = most_recent)

log_interactions <- felm(log_days ~ 
                    1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + male_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate +
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    jobs_reported + 
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate +
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current + 
      I(minority_percent^2) +
      I(minority_percent^2) + 
    I(minority_percent * median_family_income) +
    I(minority_percent * cook_pvi) +
    I(minority_percent * rural) + 
    I(minority_percent * estimate_gini_index) +
    I(minority_percent * violent_crime_rate)|lender + fips|0|zip, 
    data = most_recent)
```

```{r}
# most_recent_housing <- most_recent_housing %>%
#   mutate(lender = as.factor(lender),
#          fips = as.factor(fips),
#          renter_percent = as.double(renter_percent))
#   
# # Trying to add rent
# 
# dems <- felm(
#   business_days ~ 1 + 
#     median_family_income + 
#     minority_percent +
#     high_school_pct + 
#     married_percent + male_percent + 
#     cook_pvi + 
#     rural +
#     estimate_gini_index +
#     violent_crime_rate + 
#     renter_percent|0|0|zip,
#   data = most_recent_housing)
# ```

