---
title: "regressions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(estimatr)
library(lmtest)
library(sandwich)
library(broom)

# This is where I run all my regressions. Most of this again isn't super
# necessary for gov 50. 
```

```{r}
# most recent data

most_recent <- readRDS('ppp_allvars_1028.rds') %>%
  mutate(median_family_income = median_family_income / 1000,
         bank_ppp_issued = bank_ppp_issued / 1000,
         businesses_per_pop = businesses_per_pop / 100,
         violent_crime_rate = violent_crime_rate / 10) %>%
  mutate(zip = as.factor(zip))
```


```{r}
#residuals <-summary(all_linear_reg)$df.residual

# This is just a residual plot for my own use to look at heteroskedasticity --
# I also used the Breusch-Pagan test (bptest in R) to look at this.

ggplot(data = most_recent, mapping = aes(x = days_to_approval, 
                                         y = (days_to_approval - all_linear_reg$fitted.values))) +
  geom_jitter(alpha = 0.3, color = "dodgerblue") +
  ylim(-250, 500) +
  labs(x = "Days to Approval", y = "Residuals", title = "Waiting Time vs. Residuals")
```


```{r}
# most recent county

most_recent_county <- readRDS('counties_all_1028.rds') %>%
   mutate(median_income = median_income / 1000,
         bank_ppp_issued = bank_ppp_issued / 1000,
         
         # This is b/c we didn't do per 10,000 people before, but we want 
         # hundreds of businesses 
         # per 10,000 people, or 100
         
         businesses_per_pop = businesses_per_pop * 100,
         violent_crime_rate = violent_crime_rate / 10,
         pop_den = pop_den / 100,
         black_percent = black_percent * 100,
         white_percent = white_percent * 100) %>%
  
  # We make this a factor to let lm_robust work faster when it calculates
  # clustered SEs
  
  mutate(fips = as.factor(fips))
```

```{r}
# Straight regression -- all variables, no interactions. You can just see
# similar regressions all the way down -- most of this is self-explanatory.

all_linear_reg <- lm_robust(days_to_approval ~ 1 + median_family_income +
       black_percent +
       white_percent +
       high_school_pct +
       banks_per_pop + 
       loan_350_1mil + loan_150_350 + 
       loan_5mil_10mil +
       loan_2mil_5mil + loan_1mil_2mil +
       cook_pvi + mean_start_cases_weighted + 
       mean_start_deaths_weighted + mean_end_cases_weighted +
       mean_end_deaths_weighted + 
       bank_ppp_issued +
       rural + businesses_per_pop +
       married_percent + preference +
       requirement + 
       stay_at_home_apr +
       stay_at_home_current +
       non_essential_closure_apr +
       non_essential_closure_current + 
       unemployment_rate + 
       unemployment_rate_apr + 
       estimate_gini_index +
       violent_crime_rate +
       jobs_reported,
       most_recent, clusters = zip, se_type = "CR0")

summary(all_linear_reg)

tibble_all_linear <- tidy(all_linear_reg)

```

```{r}
all_linear_reg_b <- lm_robust(days_to_approval ~ 1 + median_family_income +
       black_percent +
       white_percent +
       high_school_pct +
       banks_per_pop + 
       loan_350_1mil + loan_150_350 + 
       loan_5mil_10mil +
       loan_2mil_5mil + loan_1mil_2mil +
       cook_pvi + mean_end_cases_weighted +
       mean_end_deaths_weighted + 
       bank_ppp_issued +
       rural + businesses_per_pop +
       married_percent + preference +
       requirement + 
       stay_at_home_current +
       non_essential_closure_current + 
       unemployment_rate + 
       estimate_gini_index +
       violent_crime_rate +
       jobs_reported,
       most_recent, clusters = zip, se_type = "CR0")

summary(all_linear_reg_b)

```
```{r}
all_linear_reg_c <- lm_robust(days_to_approval ~ 1 + median_family_income +
       black_percent + I(black_percent^2) +
       white_percent + I(white_percent^2) +
       high_school_pct +
       banks_per_pop + 
       loan_350_1mil + loan_150_350 + 
       loan_5mil_10mil +
       loan_2mil_5mil + loan_1mil_2mil +
       cook_pvi + I(cook_pvi^2) +
         mean_start_cases_weighted + I(mean_start_cases_weighted^2) +
       mean_start_deaths_weighted + I(mean_start_deaths_weighted^2) +
       mean_end_cases_weighted + I(mean_end_cases_weighted^2) +
       mean_end_deaths_weighted + I(mean_end_deaths_weighted^2) +
       bank_ppp_issued + I(bank_ppp_issued^2) +
       rural + businesses_per_pop +
       married_percent + preference +
       requirement + 
       stay_at_home_apr +
       stay_at_home_current +
       non_essential_closure_apr +
       non_essential_closure_current + 
       unemployment_rate + I(unemployment_rate^2)+
       unemployment_rate_apr + I(unemployment_rate_apr^2) +
       estimate_gini_index +
       violent_crime_rate +
       jobs_reported + I(jobs_reported^2),
       most_recent, clusters = zip, se_type = "CR0")

summary(all_linear_reg_c)

tibble_all_linear_c <- tidy(all_linear_reg_c)
```

```{r}
# Trying out a log regression to see what happens

log_reg <- most_recent %>%
  mutate(log_days = ifelse(log(days_to_approval) == -Inf, 0, log(days_to_approval)),
         log_income = ifelse(log(median_family_income) == -Inf, 0, log(median_family_income)),
         log_banks = ifelse(log(banks_per_pop) == -Inf, 0, log(banks_per_pop)),
         log_startcases = ifelse(log(mean_start_cases_weighted) == -Inf, 0, log(mean_start_cases_weighted)),
         log_endcases = ifelse(log(mean_end_cases_weighted) == -Inf, 0, log(mean_end_cases_weighted)),
         log_startdeaths = ifelse(log(mean_start_deaths_weighted) == -Inf, 0, log(mean_start_deaths_weighted)),
         log_enddeaths = ifelse(log(mean_end_deaths_weighted) == -Inf, 0, log(mean_end_deaths_weighted)),
         log_jobs = ifelse(log(jobs_reported) == -Inf, 0, log(jobs_reported)),
         log_loans = ifelse(log(bank_ppp_issued) == -Inf, 0, log(bank_ppp_issued)),
         log_biz = ifelse(log(businesses_per_pop) == -Inf, 0, log(businesses_per_pop)),
         log_crime = ifelse(log(violent_crime_rate) == -Inf, 0, log(violent_crime_rate)))

zip_log_reg <- lm_robust(log_days ~ 1 + log_income + log_banks +
       black_percent +
       white_percent +
       high_school_pct +
       log_banks + 
       loan_350_1mil + loan_150_350 + 
       loan_5mil_10mil +
       loan_2mil_5mil + loan_1mil_2mil +
       cook_pvi + 
       log_startcases + 
       log_startdeaths + log_endcases +
       log_enddeaths + 
       log_loans +
       rural + log_biz +
       married_percent + preference +
       requirement + 
       stay_at_home_apr +
       stay_at_home_current +
       non_essential_closure_apr +
       non_essential_closure_current + 
       unemployment_rate + 
       unemployment_rate_apr + 
       estimate_gini_index +
       log_crime +
       log_jobs,
       log_reg, clusters = zip, se_type = "CR0")

log_reg_zip_tibble <- tidy(zip_log_reg)
```


```{r}
# log-linear
log_linear_reg <- lm_robust(log_days ~ 1 + median_family_income +
       black_percent +
       white_percent +
       high_school_pct +
       banks_per_pop + 
       loan_350_1mil + loan_150_350 + 
       loan_5mil_10mil +
       loan_2mil_5mil + loan_1mil_2mil +
       cook_pvi + mean_start_cases_weighted + 
       mean_start_deaths_weighted + mean_end_cases_weighted +
       mean_end_deaths_weighted + 
       bank_ppp_issued +
       rural + businesses_per_pop +
       married_percent + preference +
       requirement + 
       stay_at_home_apr +
       stay_at_home_current +
       non_essential_closure_apr +
       non_essential_closure_current + 
       unemployment_rate + 
       unemployment_rate_apr + 
       estimate_gini_index +
       violent_crime_rate +
       jobs_reported,
       log_reg, clusters = zip, se_type = "CR0")

summary(log_linear_reg)

log_linear_tibble <- tidy(log_linear_reg)

```

```{r}
  
county_reg_a <- lm_robust(days_to_approval ~ 1 + median_income +
       black_percent +
       white_percent +
       high_school_pct +
       banks_per_pop + 
       loan_350_1mil + loan_150_350 + 
       loan_5mil_10mil +
       loan_2mil_5mil + loan_1mil_2mil +
       republican_percent + mean_end_cases +
       mean_end_deaths + 
       bank_ppp_issued +
       pop_den + businesses_per_pop +
       married_percent + preference +
       requirement + 
       stay_at_home_current +
       non_essential_closure_current + 
       unemployment_rate_percent + 
       estimate_gini_index +
       violent_crime_rate +
       jobs_reported,
       most_recent_county, clusters = fips, se_type = "CR0")

summary(county_reg_a)
```

```{r}

```

```{r}
county_reg_b <- lm_robust(days_to_approval ~ 1 + median_income +
       black_percent +
       white_percent +
       high_school_pct +
       banks_per_pop + 
       loan_350_1mil + loan_150_350 + 
       loan_5mil_10mil +
       loan_2mil_5mil + loan_1mil_2mil +
       republican_percent + mean_start_cases + mean_start_deaths + 
         mean_end_cases +
       mean_end_deaths + 
       bank_ppp_issued +
       pop_den + businesses_per_pop +
       married_percent + preference +
       requirement + 
       stay_at_home_apr + 
       non_essential_closure_apr + 
       stay_at_home_current +
       non_essential_closure_current + 
       unemployment_rate_percent + 
       unemployment_rate_apr + 
       estimate_gini_index +
       violent_crime_rate +
       jobs_reported,
       most_recent_county, clusters = fips, se_type = "CR0")

summary(county_reg_b)
```

