---
title: "regression_2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(estimatr)
library(lmtest)
library(sandwich)
library(broom)
library(tidyverse)
library(texreg)
library(bizdays)
library(ggeffects)

# holidays <- federalHolidays(2020, board = F, businessOnly = T)

cal <-  create.calendar(name = "mycal", weekdays=c("saturday", "sunday"))
```

```{r}
most_recent <- readRDS('most_recent_zip.rds')

most_recent_county <- readRDS('most_recent_county.rds')

```


```{r}

# One flaw I realized is that my previous days_to_approval count included
# weekends, which is why I exclude them here. There are only 1 or 2 public
# holidays and I had trouble making the biz_days function work with them,
# so those shouldn't throw off the count too much.

most_recent <- readRDS('ppp_allvars_1105.rds') %>%
  mutate(median_family_income = median_family_income / 1000,
         bank_ppp_issued = bank_ppp_issued / 1000,
         businesses_per_pop = businesses_per_pop / 100,
         violent_crime_rate = violent_crime_rate / 10,
         payroll = payroll / 1000,
         minority_percent = 100 - white_percent) %>%
  mutate(delay = ifelse(date_approved > as.Date("2020-04-16"), 1, 0),
         business_days = bizdays(as.Date("2020-04-03"), date_approved, 
                                 'mycal')) %>%
  select(-black_percent, -white_percent) %>%
  mutate(zip = as.factor(zip))

most_recent_county <- readRDS('counties_all_1105.rds') %>%
   mutate(median_income = median_income / 1000,
         bank_ppp_issued = bank_ppp_issued / 1000,
         
         # This is b/c we didn't do per 10,000 people before, but we want 
         # hundreds of businesses 
         # per 10,000 people, or 100
         
         businesses_per_pop = businesses_per_pop * 100,
         violent_crime_rate = violent_crime_rate / 10,
         pop_den = pop_den / 100,
         black_percent = black_percent * 100,
         white_percent = white_percent * 100,
         gdp = gdp / 1000) %>%
  mutate(delay = ifelse(date_approved > as.Date("2020-04-16"), 1, 0),
         business_days = bizdays(as.Date("2020-04-03"), date_approved, 
                                 'mycal')) %>%
  mutate(minority_percent = 100 - white_percent) %>%
  select(-black_percent) %>%
  
  # We make this a factor to let lm_robust work faster when it calculates
  # clustered SEs
  
  mutate(fips = as.factor(fips))
```


```{r}
# Regression 1: Demographics Only

demographics <- lm_robust(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate,
  most_recent, clusters = zip, se_type = "CR0")
```


```{r}
# Regression 2: Demographics and Loan-Specific

loan_spec <- lm_robust(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported,
  most_recent, clusters = zip, se_type = "CR0")
```


```{r}
# Regression 3: Including economics

econ <- lm_robust(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    delay +
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate,
  most_recent, clusters = zip, se_type = "CR0")
```


```{r}
# Regression 4: Including COVID

covid <- lm_robust(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current,
  most_recent, clusters = zip, se_type = "CR0")
```


```{r}

# Generating ggeffects dataframes to plot this in Shiny -- not relevant
# for other classes

marginal_race <- ggeffect(covid, terms = "minority_percent")
```


```{r}
interactions <- lm_robust(
  business_days ~ 1 + 
    median_family_income + 
    minority_percent +
    high_school_pct + 
    married_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2) + 
    I(minority_percent * median_family_income) +
    I(minority_percent * cook_pvi) +
    I(minority_percent * rural) + 
    I(minority_percent * estimate_gini_index) +
    I(minority_percent * violent_crime_rate),
  most_recent, clusters = zip, se_type = "CR0")
```


```{r}
# marginal_race_sq <- ggeffect(interactions, terms = c("minority_percent", "I(minority_percent^2)"))
```


```{r}
ggplot(data = most_recent, mapping = aes(x = business_days, 
                                         y = (abs(business_days - interactions$fitted.values)))) +
  geom_jitter(alpha = 0.3, color = "dodgerblue") +
  ylim(0, 150) +
  labs(x = "Days to Approval", y = "Residuals", title = "Waiting Time vs. Residuals") +
  theme_classic()
```


```{r}
# County level

county_dems <- lm_robust(
  business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate,
  most_recent_county, clusters = fips, se_type = "CR0")
```


```{r}
county_loan <- lm_robust(
  business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay +
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported,
  most_recent_county, clusters = fips, se_type = "CR0")
```


```{r}
county_econ <- lm_robust(
  business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent,
  most_recent_county, clusters = fips, se_type = "CR0")
```


```{r}
county_covid <- lm_robust(
  business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current,
  most_recent_county, clusters = fips, se_type = "CR0")
```


```{r}

# Generating ggeffects dataframes to plot this in Shiny -- not relevant
# for other classes

marginal_race_county <- ggeffect(county_covid, terms = "minority_percent")
```


```{r}
county_interactions <- lm_robust(
  business_days ~ 1 + 
    median_income + 
    minority_percent +
    
    high_school_pct + 
    married_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    delay + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(minority_percent^2) + 
    I(minority_percent * median_income) +
    I(minority_percent * republican_percent) +
    I(minority_percent * pop_den) + 
    I(minority_percent * estimate_gini_index) +
    I(minority_percent * violent_crime_rate),
  most_recent_county, clusters = fips, se_type = "CR0")
```


```{r}
# Trying log-linear using log(x+1) to avoid the zeroes problem

most_recent_log <- most_recent %>%
  mutate(log_days = log(days_to_approval + 1)) %>%
  mutate(sqrt_days = sqrt(days_to_approval))

most_recent_county_log <- most_recent_county %>%
  mutate(log_days = log(days_to_approval + 1)) %>%
  mutate(sqrt_days = sqrt(days_to_approval))
```


```{r}
interactions_sqrt <- lm_robust(
  sqrt_days ~ 1 + 
    median_family_income + 
    black_percent +
    white_percent +
    high_school_pct + 
    married_percent + 
    cook_pvi + 
    rural +
    estimate_gini_index +
    violent_crime_rate + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    payroll +
    unemployment_rate_apr + 
    unemployment_rate + 
    mean_start_cases_weighted +
    mean_start_deaths_weighted + 
    mean_end_cases_weighted +
    mean_end_deaths_weighted + 
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(black_percent^2) + 
    I(white_percent^2) + 
    I(black_percent * median_family_income) +
    I(black_percent * cook_pvi) +
    I(black_percent * rural) + 
    I(black_percent * estimate_gini_index) +
    I(black_percent * violent_crime_rate),
  most_recent_log, clusters = zip, se_type = "CR0")
```


```{r}
county_interactions_sqrt <- lm_robust(
  sqrt_days ~ 1 + 
    median_income + 
    black_percent +
    white_percent +
    high_school_pct + 
    married_percent + 
    republican_percent + 
    pop_den +
    estimate_gini_index +
    violent_crime_rate + 
    loan_150_350 +
    loan_350_1mil +
    loan_1mil_2mil +
    loan_2mil_5mil + 
    loan_5mil_10mil + 
    preference + 
    requirement + 
    bank_ppp_issued + 
    jobs_reported +
    banks_per_pop + 
    businesses_per_pop + 
    gdp +
    unemployment_rate_apr + 
    unemployment_rate_percent + 
    mean_start_cases +
    mean_start_deaths + 
    mean_end_cases +
    mean_end_deaths +
    stay_at_home_apr + 
    stay_at_home_current + 
    non_essential_closure_apr + 
    non_essential_closure_current +
    I(black_percent^2) + 
    I(white_percent^2) + 
    I(black_percent * median_income) +
    I(black_percent * republican_percent) +
    I(black_percent * pop_den) + 
    I(black_percent * estimate_gini_index) +
    I(black_percent * violent_crime_rate),
  most_recent_county_log, clusters = fips, se_type = "CR0")
```

