---
title: "bank loan dummies"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(tidyverse)

loan_data <- readRDS("ppp_covidadj_1018.rds")
old_data <- readRDS("ppp_loanonly_all_loans.rds")
```


```{r}
banks <- loan_data %>%
  select(lender) %>%
  group_by(lender) %>%
  summarize(number_of_loans = n(), .groups = "drop") %>%
  ungroup() %>%
  mutate(lender = tolower(lender))

banks_gov_project <- loan_data %>%
  select(lender) %>%
  group_by(lender) %>%
  summarize(number_of_loans = n(), .groups = "drop") %>%
  filter(number_of_loans >= 1000)
```


```{r}
# Counting the number of loans per bank
loan_numbers <- old_data %>%
  select(lender) %>%
  group_by(lender) %>%
  summarize(bank_ppp_issued = n(), .groups = "drop")

ppp_allvars_1018 <- left_join(loan_data, loan_numbers, by = "lender") %>%
  rename("cook_pvi" = "pct", 
         "black_percent" = "percent_estimate_race_total_population_one_race_black_or_african_american",
         "White_percent" = "percent_estimate_race_total_population_one_race_white",
         "median_family_income" = "estimate_median_income_dollars_families_families",
         "population" = "estimate_total") %>%
  select(-loan_range)
```


```{r}
# Rural data dummy coding
rural <- read_excel("raw_data/crosswalks/forhp-eligible-zips.xlsx") %>%
  clean_names() %>%
  select(-state) %>%
  mutate(rural = 1)

ppp_allvars_1018_rural <- left_join(ppp_allvars_1018, rural, by = "zip") %>%
  
ppp_allvars_1018_rural <- ppp_allvars_1018_rural %>%
  mutate(rural = replace_na(rural, 0)) %>%
  mutate(rural = as.double(rural))
  
```


```{r}
bank_deposits <- read_csv("raw_data/fdic/All_Reports_20200630_Total_Deposits.csv") %>%
  select(name, dep) %>%
  mutate(dep = as.double(dep), name = tolower(name))
```


```{r}
left_join(banks, bank_deposits, by = c("lender" = "name")) %>%
  group_by(lender) %>%
  filter(is.na(dep))
```


```{r}
#ppp_allvars_1018_rural <- readRDS('ppp_allvars_1018_rural.rds')
test_regression <-
  lm(ppp_allvars_1018_rural$days_to_approval ~ 1 + ppp_allvars_1018_rural$median_family_income +
       ppp_allvars_1018_rural$black_percent +
       ppp_allvars_1018_rural$White_percent + ppp_allvars_1018_rural$high_school_pct +
       ppp_allvars_1018_rural$banks_per_pop + 
       ppp_allvars_1018_rural$loan_350_1mil + ppp_allvars_1018_rural$loan_150_350 + 
       ppp_allvars_1018_rural$loan_5mil_10mil +
       ppp_allvars_1018_rural$loan_2mil_5mil + ppp_allvars_1018_rural$loan_1mil_2mil +
       ppp_allvars_1018_rural$cook_pvi + ppp_allvars_1018_rural$mean_start_cases_weighted + 
       ppp_allvars_1018_rural$mean_start_deaths_weighted + ppp_allvars_1018_rural$bank_ppp_issued +
       ppp_allvars_1018_rural$rural)

summary(test_regression)
```
